// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/alliance_recruitment.proto

package alliance_recruitment

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllianceRecruitmentInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceRecruitmentInformationRequest) Reset() {
	*x = AllianceRecruitmentInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceRecruitmentInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceRecruitmentInformationRequest) ProtoMessage() {}

func (x *AllianceRecruitmentInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceRecruitmentInformationRequest.ProtoReflect.Descriptor instead.
func (*AllianceRecruitmentInformationRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{0}
}

type AllianceRecruitmentUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Information *common.AllianceRecruitmentInformation `protobuf:"bytes,1,opt,name=information,proto3" json:"information,omitempty"`
}

func (x *AllianceRecruitmentUpdateRequest) Reset() {
	*x = AllianceRecruitmentUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceRecruitmentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceRecruitmentUpdateRequest) ProtoMessage() {}

func (x *AllianceRecruitmentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceRecruitmentUpdateRequest.ProtoReflect.Descriptor instead.
func (*AllianceRecruitmentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{1}
}

func (x *AllianceRecruitmentUpdateRequest) GetInformation() *common.AllianceRecruitmentInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

type AllianceRecruitmentInformationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Information *common.AllianceRecruitmentInformation `protobuf:"bytes,1,opt,name=information,proto3" json:"information,omitempty"`
}

func (x *AllianceRecruitmentInformationEvent) Reset() {
	*x = AllianceRecruitmentInformationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceRecruitmentInformationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceRecruitmentInformationEvent) ProtoMessage() {}

func (x *AllianceRecruitmentInformationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceRecruitmentInformationEvent.ProtoReflect.Descriptor instead.
func (*AllianceRecruitmentInformationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{2}
}

func (x *AllianceRecruitmentInformationEvent) GetInformation() *common.AllianceRecruitmentInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

type AllianceRecruitmentAutomaticJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceUid string `protobuf:"bytes,1,opt,name=alliance_uid,json=allianceUid,proto3" json:"alliance_uid,omitempty"`
}

func (x *AllianceRecruitmentAutomaticJoinRequest) Reset() {
	*x = AllianceRecruitmentAutomaticJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceRecruitmentAutomaticJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceRecruitmentAutomaticJoinRequest) ProtoMessage() {}

func (x *AllianceRecruitmentAutomaticJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceRecruitmentAutomaticJoinRequest.ProtoReflect.Descriptor instead.
func (*AllianceRecruitmentAutomaticJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{3}
}

func (x *AllianceRecruitmentAutomaticJoinRequest) GetAllianceUid() string {
	if x != nil {
		return x.AllianceUid
	}
	return ""
}

type AllianceRecruitmentInvalidateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceRecruitmentInvalidateEvent) Reset() {
	*x = AllianceRecruitmentInvalidateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceRecruitmentInvalidateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceRecruitmentInvalidateEvent) ProtoMessage() {}

func (x *AllianceRecruitmentInvalidateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceRecruitmentInvalidateEvent.ProtoReflect.Descriptor instead.
func (*AllianceRecruitmentInvalidateEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{4}
}

type AllianceApplicationSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceUid string `protobuf:"bytes,1,opt,name=alliance_uid,json=allianceUid,proto3" json:"alliance_uid,omitempty"`
	Text        string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AllianceApplicationSubmitRequest) Reset() {
	*x = AllianceApplicationSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationSubmitRequest) ProtoMessage() {}

func (x *AllianceApplicationSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationSubmitRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationSubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{5}
}

func (x *AllianceApplicationSubmitRequest) GetAllianceUid() string {
	if x != nil {
		return x.AllianceUid
	}
	return ""
}

func (x *AllianceApplicationSubmitRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AllianceApplicationUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceUid string `protobuf:"bytes,1,opt,name=alliance_uid,json=allianceUid,proto3" json:"alliance_uid,omitempty"`
	Text        string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AllianceApplicationUpdateRequest) Reset() {
	*x = AllianceApplicationUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationUpdateRequest) ProtoMessage() {}

func (x *AllianceApplicationUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationUpdateRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{6}
}

func (x *AllianceApplicationUpdateRequest) GetAllianceUid() string {
	if x != nil {
		return x.AllianceUid
	}
	return ""
}

func (x *AllianceApplicationUpdateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AllianceApplicationDeletionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceApplicationDeletionRequest) Reset() {
	*x = AllianceApplicationDeletionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationDeletionRequest) ProtoMessage() {}

func (x *AllianceApplicationDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationDeletionRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationDeletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{7}
}

type AllianceApplicationListenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *AllianceApplicationListenRequest) Reset() {
	*x = AllianceApplicationListenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationListenRequest) ProtoMessage() {}

func (x *AllianceApplicationListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationListenRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationListenRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{8}
}

func (x *AllianceApplicationListenRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type AllianceApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceApplicationRequest) Reset() {
	*x = AllianceApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationRequest) ProtoMessage() {}

func (x *AllianceApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{9}
}

type AllianceApplicationListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AllianceApplicationListRequest) Reset() {
	*x = AllianceApplicationListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationListRequest) ProtoMessage() {}

func (x *AllianceApplicationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationListRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationListRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{10}
}

func (x *AllianceApplicationListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AllianceApplicationListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AllianceApplicationAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted bool  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *AllianceApplicationAnswerRequest) Reset() {
	*x = AllianceApplicationAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationAnswerRequest) ProtoMessage() {}

func (x *AllianceApplicationAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationAnswerRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{11}
}

func (x *AllianceApplicationAnswerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AllianceApplicationAnswerRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type AllianceApplicationPresenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceApplicationPresenceRequest) Reset() {
	*x = AllianceApplicationPresenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationPresenceRequest) ProtoMessage() {}

func (x *AllianceApplicationPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationPresenceRequest.ProtoReflect.Descriptor instead.
func (*AllianceApplicationPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{12}
}

type AllianceApplicationDeletedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AllianceApplicationDeletedEvent) Reset() {
	*x = AllianceApplicationDeletedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationDeletedEvent) ProtoMessage() {}

func (x *AllianceApplicationDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationDeletedEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationDeletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{13}
}

func (x *AllianceApplicationDeletedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AllianceApplicationInformationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alliance               *common.AllianceInformation          `protobuf:"bytes,1,opt,name=alliance,proto3" json:"alliance,omitempty"`
	ApplicationInformation *common.SocialApplicationInformation `protobuf:"bytes,2,opt,name=application_information,json=applicationInformation,proto3" json:"application_information,omitempty"`
}

func (x *AllianceApplicationInformationEvent) Reset() {
	*x = AllianceApplicationInformationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationInformationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationInformationEvent) ProtoMessage() {}

func (x *AllianceApplicationInformationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationInformationEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationInformationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{14}
}

func (x *AllianceApplicationInformationEvent) GetAlliance() *common.AllianceInformation {
	if x != nil {
		return x.Alliance
	}
	return nil
}

func (x *AllianceApplicationInformationEvent) GetApplicationInformation() *common.SocialApplicationInformation {
	if x != nil {
		return x.ApplicationInformation
	}
	return nil
}

type AllianceApplicationNoInformationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceApplicationNoInformationEvent) Reset() {
	*x = AllianceApplicationNoInformationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationNoInformationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationNoInformationEvent) ProtoMessage() {}

func (x *AllianceApplicationNoInformationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationNoInformationEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationNoInformationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{15}
}

type AllianceApplicationResponseEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted            bool                        `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AllianceInformation *common.AllianceInformation `protobuf:"bytes,2,opt,name=alliance_information,json=allianceInformation,proto3" json:"alliance_information,omitempty"`
}

func (x *AllianceApplicationResponseEvent) Reset() {
	*x = AllianceApplicationResponseEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationResponseEvent) ProtoMessage() {}

func (x *AllianceApplicationResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationResponseEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationResponseEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{16}
}

func (x *AllianceApplicationResponseEvent) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AllianceApplicationResponseEvent) GetAllianceInformation() *common.AllianceInformation {
	if x != nil {
		return x.AllianceInformation
	}
	return nil
}

type AllianceApplicationListEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset  int64                                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count   int64                                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total   int64                                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Applies []*common.SocialApplicationInformation `protobuf:"bytes,4,rep,name=applies,proto3" json:"applies,omitempty"`
}

func (x *AllianceApplicationListEvent) Reset() {
	*x = AllianceApplicationListEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationListEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationListEvent) ProtoMessage() {}

func (x *AllianceApplicationListEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationListEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationListEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{17}
}

func (x *AllianceApplicationListEvent) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AllianceApplicationListEvent) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AllianceApplicationListEvent) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AllianceApplicationListEvent) GetApplies() []*common.SocialApplicationInformation {
	if x != nil {
		return x.Applies
	}
	return nil
}

type AllianceApplicationModifiedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apply    *common.SocialApplicationInformation `protobuf:"bytes,1,opt,name=apply,proto3" json:"apply,omitempty"`
	State    common.SocialApplicationState        `protobuf:"varint,2,opt,name=state,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialApplicationState" json:"state,omitempty"`
	PlayerId int64                                `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *AllianceApplicationModifiedEvent) Reset() {
	*x = AllianceApplicationModifiedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationModifiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationModifiedEvent) ProtoMessage() {}

func (x *AllianceApplicationModifiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationModifiedEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationModifiedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{18}
}

func (x *AllianceApplicationModifiedEvent) GetApply() *common.SocialApplicationInformation {
	if x != nil {
		return x.Apply
	}
	return nil
}

func (x *AllianceApplicationModifiedEvent) GetState() common.SocialApplicationState {
	if x != nil {
		return x.State
	}
	return common.SocialApplicationState(0)
}

func (x *AllianceApplicationModifiedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type AllianceApplicationReceivedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerId   int64  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *AllianceApplicationReceivedEvent) Reset() {
	*x = AllianceApplicationReceivedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationReceivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationReceivedEvent) ProtoMessage() {}

func (x *AllianceApplicationReceivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationReceivedEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationReceivedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{19}
}

func (x *AllianceApplicationReceivedEvent) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *AllianceApplicationReceivedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type AllianceApplicationPresenceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Presence bool `protobuf:"varint,1,opt,name=presence,proto3" json:"presence,omitempty"`
}

func (x *AllianceApplicationPresenceEvent) Reset() {
	*x = AllianceApplicationPresenceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_recruitment_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceApplicationPresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceApplicationPresenceEvent) ProtoMessage() {}

func (x *AllianceApplicationPresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_recruitment_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceApplicationPresenceEvent.ProtoReflect.Descriptor instead.
func (*AllianceApplicationPresenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_recruitment_proto_rawDescGZIP(), []int{20}
}

func (x *AllianceApplicationPresenceEvent) GetPresence() bool {
	if x != nil {
		return x.Presence
	}
	return false
}

var File_proto_game_alliance_recruitment_proto protoreflect.FileDescriptor

var file_proto_game_alliance_recruitment_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3a, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b,
	0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x25, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x20, 0x41,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x6e, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d,
	0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x63, 0x72,
	0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x95, 0x01, 0x0a, 0x23, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x63, 0x72,
	0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x6e, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x27, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x22, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x20, 0x41,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x55,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x59, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x24, 0x0a, 0x22, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4e, 0x0a, 0x1e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x5b, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0x24, 0x0a, 0x22,
	0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3b, 0x0a, 0x1f, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x8a, 0x02, 0x0a, 0x23, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x61, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x17, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61,
	0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x16, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x25,
	0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x74, 0x0a, 0x14, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d,
	0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc8, 0x01, 0x0a,
	0x1c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x64, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0xfd, 0x01, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x60, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x5a,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x44, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x20, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x6f, 0x2d,
	0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_alliance_recruitment_proto_rawDescOnce sync.Once
	file_proto_game_alliance_recruitment_proto_rawDescData = file_proto_game_alliance_recruitment_proto_rawDesc
)

func file_proto_game_alliance_recruitment_proto_rawDescGZIP() []byte {
	file_proto_game_alliance_recruitment_proto_rawDescOnce.Do(func() {
		file_proto_game_alliance_recruitment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_alliance_recruitment_proto_rawDescData)
	})
	return file_proto_game_alliance_recruitment_proto_rawDescData
}

var file_proto_game_alliance_recruitment_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_game_alliance_recruitment_proto_goTypes = []any{
	(*AllianceRecruitmentInformationRequest)(nil),   // 0: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentInformationRequest
	(*AllianceRecruitmentUpdateRequest)(nil),        // 1: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentUpdateRequest
	(*AllianceRecruitmentInformationEvent)(nil),     // 2: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentInformationEvent
	(*AllianceRecruitmentAutomaticJoinRequest)(nil), // 3: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentAutomaticJoinRequest
	(*AllianceRecruitmentInvalidateEvent)(nil),      // 4: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentInvalidateEvent
	(*AllianceApplicationSubmitRequest)(nil),        // 5: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationSubmitRequest
	(*AllianceApplicationUpdateRequest)(nil),        // 6: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationUpdateRequest
	(*AllianceApplicationDeletionRequest)(nil),      // 7: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationDeletionRequest
	(*AllianceApplicationListenRequest)(nil),        // 8: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationListenRequest
	(*AllianceApplicationRequest)(nil),              // 9: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationRequest
	(*AllianceApplicationListRequest)(nil),          // 10: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationListRequest
	(*AllianceApplicationAnswerRequest)(nil),        // 11: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationAnswerRequest
	(*AllianceApplicationPresenceRequest)(nil),      // 12: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationPresenceRequest
	(*AllianceApplicationDeletedEvent)(nil),         // 13: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationDeletedEvent
	(*AllianceApplicationInformationEvent)(nil),     // 14: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationInformationEvent
	(*AllianceApplicationNoInformationEvent)(nil),   // 15: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationNoInformationEvent
	(*AllianceApplicationResponseEvent)(nil),        // 16: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationResponseEvent
	(*AllianceApplicationListEvent)(nil),            // 17: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationListEvent
	(*AllianceApplicationModifiedEvent)(nil),        // 18: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationModifiedEvent
	(*AllianceApplicationReceivedEvent)(nil),        // 19: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationReceivedEvent
	(*AllianceApplicationPresenceEvent)(nil),        // 20: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationPresenceEvent
	(*common.AllianceRecruitmentInformation)(nil),   // 21: com.ankama.dofus.server.game.protocol.common.AllianceRecruitmentInformation
	(*common.AllianceInformation)(nil),              // 22: com.ankama.dofus.server.game.protocol.common.AllianceInformation
	(*common.SocialApplicationInformation)(nil),     // 23: com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	(common.SocialApplicationState)(0),              // 24: com.ankama.dofus.server.game.protocol.common.SocialApplicationState
}
var file_proto_game_alliance_recruitment_proto_depIdxs = []int32{
	21, // 0: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentUpdateRequest.information:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceRecruitmentInformation
	21, // 1: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceRecruitmentInformationEvent.information:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceRecruitmentInformation
	22, // 2: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationInformationEvent.alliance:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceInformation
	23, // 3: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationInformationEvent.application_information:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	22, // 4: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationResponseEvent.alliance_information:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceInformation
	23, // 5: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationListEvent.applies:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	23, // 6: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationModifiedEvent.apply:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	24, // 7: com.ankama.dofus.server.game.protocol.alliance.recruitment.AllianceApplicationModifiedEvent.state:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_game_alliance_recruitment_proto_init() }
func file_proto_game_alliance_recruitment_proto_init() {
	if File_proto_game_alliance_recruitment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_alliance_recruitment_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceRecruitmentInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceRecruitmentUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceRecruitmentInformationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceRecruitmentAutomaticJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceRecruitmentInvalidateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationDeletionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationListenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationPresenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationDeletedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationInformationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationNoInformationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationResponseEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationListEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationModifiedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationReceivedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_recruitment_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceApplicationPresenceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_alliance_recruitment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_alliance_recruitment_proto_goTypes,
		DependencyIndexes: file_proto_game_alliance_recruitment_proto_depIdxs,
		MessageInfos:      file_proto_game_alliance_recruitment_proto_msgTypes,
	}.Build()
	File_proto_game_alliance_recruitment_proto = out.File
	file_proto_game_alliance_recruitment_proto_rawDesc = nil
	file_proto_game_alliance_recruitment_proto_goTypes = nil
	file_proto_game_alliance_recruitment_proto_depIdxs = nil
}
