// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/element.proto

package element

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchasableDialogEvent_Action int32

const (
	PurchasableDialogEvent_BUY  PurchasableDialogEvent_Action = 0
	PurchasableDialogEvent_SELL PurchasableDialogEvent_Action = 1
)

// Enum value maps for PurchasableDialogEvent_Action.
var (
	PurchasableDialogEvent_Action_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	PurchasableDialogEvent_Action_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x PurchasableDialogEvent_Action) Enum() *PurchasableDialogEvent_Action {
	p := new(PurchasableDialogEvent_Action)
	*p = x
	return p
}

func (x PurchasableDialogEvent_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurchasableDialogEvent_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_element_proto_enumTypes[0].Descriptor()
}

func (PurchasableDialogEvent_Action) Type() protoreflect.EnumType {
	return &file_proto_game_element_proto_enumTypes[0]
}

func (x PurchasableDialogEvent_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurchasableDialogEvent_Action.Descriptor instead.
func (PurchasableDialogEvent_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{2, 0}
}

type LockableShowCodeDialogEvent_Action int32

const (
	LockableShowCodeDialogEvent_CHANGE LockableShowCodeDialogEvent_Action = 0
	LockableShowCodeDialogEvent_USE    LockableShowCodeDialogEvent_Action = 1
)

// Enum value maps for LockableShowCodeDialogEvent_Action.
var (
	LockableShowCodeDialogEvent_Action_name = map[int32]string{
		0: "CHANGE",
		1: "USE",
	}
	LockableShowCodeDialogEvent_Action_value = map[string]int32{
		"CHANGE": 0,
		"USE":    1,
	}
)

func (x LockableShowCodeDialogEvent_Action) Enum() *LockableShowCodeDialogEvent_Action {
	p := new(LockableShowCodeDialogEvent_Action)
	*p = x
	return p
}

func (x LockableShowCodeDialogEvent_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockableShowCodeDialogEvent_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_element_proto_enumTypes[1].Descriptor()
}

func (LockableShowCodeDialogEvent_Action) Type() protoreflect.EnumType {
	return &file_proto_game_element_proto_enumTypes[1]
}

func (x LockableShowCodeDialogEvent_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockableShowCodeDialogEvent_Action.Descriptor instead.
func (LockableShowCodeDialogEvent_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{3, 0}
}

type LockableCodeResultEvent_LockableResult int32

const (
	LockableCodeResultEvent_UNLOCKED         LockableCodeResultEvent_LockableResult = 0
	LockableCodeResultEvent_CODE_ERROR       LockableCodeResultEvent_LockableResult = 1
	LockableCodeResultEvent_UNLOCK_FORBIDDEN LockableCodeResultEvent_LockableResult = 2
)

// Enum value maps for LockableCodeResultEvent_LockableResult.
var (
	LockableCodeResultEvent_LockableResult_name = map[int32]string{
		0: "UNLOCKED",
		1: "CODE_ERROR",
		2: "UNLOCK_FORBIDDEN",
	}
	LockableCodeResultEvent_LockableResult_value = map[string]int32{
		"UNLOCKED":         0,
		"CODE_ERROR":       1,
		"UNLOCK_FORBIDDEN": 2,
	}
)

func (x LockableCodeResultEvent_LockableResult) Enum() *LockableCodeResultEvent_LockableResult {
	p := new(LockableCodeResultEvent_LockableResult)
	*p = x
	return p
}

func (x LockableCodeResultEvent_LockableResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockableCodeResultEvent_LockableResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_element_proto_enumTypes[2].Descriptor()
}

func (LockableCodeResultEvent_LockableResult) Type() protoreflect.EnumType {
	return &file_proto_game_element_proto_enumTypes[2]
}

func (x LockableCodeResultEvent_LockableResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockableCodeResultEvent_LockableResult.Descriptor instead.
func (LockableCodeResultEvent_LockableResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{4, 0}
}

type LockableUseCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LockableUseCodeRequest) Reset() {
	*x = LockableUseCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockableUseCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockableUseCodeRequest) ProtoMessage() {}

func (x *LockableUseCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockableUseCodeRequest.ProtoReflect.Descriptor instead.
func (*LockableUseCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{0}
}

func (x *LockableUseCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LockableChangeCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LockableChangeCodeRequest) Reset() {
	*x = LockableChangeCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockableChangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockableChangeCodeRequest) ProtoMessage() {}

func (x *LockableChangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockableChangeCodeRequest.ProtoReflect.Descriptor instead.
func (*LockableChangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{1}
}

func (x *LockableChangeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PurchasableDialogEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action                PurchasableDialogEvent_Action `protobuf:"varint,1,opt,name=action,proto3,enum=com.ankama.dofus.server.game.protocol.element.PurchasableDialogEvent_Action" json:"action,omitempty"`
	PurchasableId         int64                         `protobuf:"varint,2,opt,name=purchasable_id,json=purchasableId,proto3" json:"purchasable_id,omitempty"`
	PurchasableInstanceId int32                         `protobuf:"varint,3,opt,name=purchasable_instance_id,json=purchasableInstanceId,proto3" json:"purchasable_instance_id,omitempty"`
	SecondHand            bool                          `protobuf:"varint,4,opt,name=second_hand,json=secondHand,proto3" json:"second_hand,omitempty"`
	Price                 int64                         `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *PurchasableDialogEvent) Reset() {
	*x = PurchasableDialogEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchasableDialogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasableDialogEvent) ProtoMessage() {}

func (x *PurchasableDialogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasableDialogEvent.ProtoReflect.Descriptor instead.
func (*PurchasableDialogEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{2}
}

func (x *PurchasableDialogEvent) GetAction() PurchasableDialogEvent_Action {
	if x != nil {
		return x.Action
	}
	return PurchasableDialogEvent_BUY
}

func (x *PurchasableDialogEvent) GetPurchasableId() int64 {
	if x != nil {
		return x.PurchasableId
	}
	return 0
}

func (x *PurchasableDialogEvent) GetPurchasableInstanceId() int32 {
	if x != nil {
		return x.PurchasableInstanceId
	}
	return 0
}

func (x *PurchasableDialogEvent) GetSecondHand() bool {
	if x != nil {
		return x.SecondHand
	}
	return false
}

func (x *PurchasableDialogEvent) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type LockableShowCodeDialogEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   LockableShowCodeDialogEvent_Action `protobuf:"varint,1,opt,name=action,proto3,enum=com.ankama.dofus.server.game.protocol.element.LockableShowCodeDialogEvent_Action" json:"action,omitempty"`
	CodeSize int32                              `protobuf:"varint,2,opt,name=code_size,json=codeSize,proto3" json:"code_size,omitempty"`
}

func (x *LockableShowCodeDialogEvent) Reset() {
	*x = LockableShowCodeDialogEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockableShowCodeDialogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockableShowCodeDialogEvent) ProtoMessage() {}

func (x *LockableShowCodeDialogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockableShowCodeDialogEvent.ProtoReflect.Descriptor instead.
func (*LockableShowCodeDialogEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{3}
}

func (x *LockableShowCodeDialogEvent) GetAction() LockableShowCodeDialogEvent_Action {
	if x != nil {
		return x.Action
	}
	return LockableShowCodeDialogEvent_CHANGE
}

func (x *LockableShowCodeDialogEvent) GetCodeSize() int32 {
	if x != nil {
		return x.CodeSize
	}
	return 0
}

type LockableCodeResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result LockableCodeResultEvent_LockableResult `protobuf:"varint,1,opt,name=result,proto3,enum=com.ankama.dofus.server.game.protocol.element.LockableCodeResultEvent_LockableResult" json:"result,omitempty"`
}

func (x *LockableCodeResultEvent) Reset() {
	*x = LockableCodeResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockableCodeResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockableCodeResultEvent) ProtoMessage() {}

func (x *LockableCodeResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockableCodeResultEvent.ProtoReflect.Descriptor instead.
func (*LockableCodeResultEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{4}
}

func (x *LockableCodeResultEvent) GetResult() LockableCodeResultEvent_LockableResult {
	if x != nil {
		return x.Result
	}
	return LockableCodeResultEvent_UNLOCKED
}

type LockableStateUpdateHouseDoorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseId         int32 `protobuf:"varint,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	HouseInstanceId int32 `protobuf:"varint,2,opt,name=house_instance_id,json=houseInstanceId,proto3" json:"house_instance_id,omitempty"`
	SecondHand      bool  `protobuf:"varint,3,opt,name=second_hand,json=secondHand,proto3" json:"second_hand,omitempty"`
	Locked          bool  `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
}

func (x *LockableStateUpdateHouseDoorEvent) Reset() {
	*x = LockableStateUpdateHouseDoorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_element_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockableStateUpdateHouseDoorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockableStateUpdateHouseDoorEvent) ProtoMessage() {}

func (x *LockableStateUpdateHouseDoorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_element_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockableStateUpdateHouseDoorEvent.ProtoReflect.Descriptor instead.
func (*LockableStateUpdateHouseDoorEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_element_proto_rawDescGZIP(), []int{5}
}

func (x *LockableStateUpdateHouseDoorEvent) GetHouseId() int32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *LockableStateUpdateHouseDoorEvent) GetHouseInstanceId() int32 {
	if x != nil {
		return x.HouseInstanceId
	}
	return 0
}

func (x *LockableStateUpdateHouseDoorEvent) GetSecondHand() bool {
	if x != nil {
		return x.SecondHand
	}
	return false
}

func (x *LockableStateUpdateHouseDoorEvent) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

var File_proto_game_element_proto protoreflect.FileDescriptor

var file_proto_game_element_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x4c, 0x6f, 0x63,
	0x6b, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2f, 0x0a, 0x19, 0x4c, 0x6f, 0x63, 0x6b, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xb1, 0x02, 0x0a, 0x16, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x64, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x4c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x36, 0x0a, 0x17, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x15, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x1b, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x59,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x22, 0xc4, 0x01, 0x0a,
	0x1b, 0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x43, 0x6f, 0x64,
	0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x69, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x51, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x6f, 0x63,
	0x6b, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x43, 0x6f, 0x64, 0x65, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x1d, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53,
	0x45, 0x10, 0x01, 0x22, 0xce, 0x01, 0x0a, 0x17, 0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x6d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x55, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66,
	0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x44,
	0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x46, 0x4f, 0x52, 0x42, 0x49, 0x44, 0x44,
	0x45, 0x4e, 0x10, 0x02, 0x22, 0xa3, 0x01, 0x0a, 0x21, 0x4c, 0x6f, 0x63, 0x6b, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x44, 0x6f, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x48, 0x61,
	0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x6f,
	0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_element_proto_rawDescOnce sync.Once
	file_proto_game_element_proto_rawDescData = file_proto_game_element_proto_rawDesc
)

func file_proto_game_element_proto_rawDescGZIP() []byte {
	file_proto_game_element_proto_rawDescOnce.Do(func() {
		file_proto_game_element_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_element_proto_rawDescData)
	})
	return file_proto_game_element_proto_rawDescData
}

var file_proto_game_element_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_game_element_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_game_element_proto_goTypes = []any{
	(PurchasableDialogEvent_Action)(0),          // 0: com.ankama.dofus.server.game.protocol.element.PurchasableDialogEvent.Action
	(LockableShowCodeDialogEvent_Action)(0),     // 1: com.ankama.dofus.server.game.protocol.element.LockableShowCodeDialogEvent.Action
	(LockableCodeResultEvent_LockableResult)(0), // 2: com.ankama.dofus.server.game.protocol.element.LockableCodeResultEvent.LockableResult
	(*LockableUseCodeRequest)(nil),              // 3: com.ankama.dofus.server.game.protocol.element.LockableUseCodeRequest
	(*LockableChangeCodeRequest)(nil),           // 4: com.ankama.dofus.server.game.protocol.element.LockableChangeCodeRequest
	(*PurchasableDialogEvent)(nil),              // 5: com.ankama.dofus.server.game.protocol.element.PurchasableDialogEvent
	(*LockableShowCodeDialogEvent)(nil),         // 6: com.ankama.dofus.server.game.protocol.element.LockableShowCodeDialogEvent
	(*LockableCodeResultEvent)(nil),             // 7: com.ankama.dofus.server.game.protocol.element.LockableCodeResultEvent
	(*LockableStateUpdateHouseDoorEvent)(nil),   // 8: com.ankama.dofus.server.game.protocol.element.LockableStateUpdateHouseDoorEvent
}
var file_proto_game_element_proto_depIdxs = []int32{
	0, // 0: com.ankama.dofus.server.game.protocol.element.PurchasableDialogEvent.action:type_name -> com.ankama.dofus.server.game.protocol.element.PurchasableDialogEvent.Action
	1, // 1: com.ankama.dofus.server.game.protocol.element.LockableShowCodeDialogEvent.action:type_name -> com.ankama.dofus.server.game.protocol.element.LockableShowCodeDialogEvent.Action
	2, // 2: com.ankama.dofus.server.game.protocol.element.LockableCodeResultEvent.result:type_name -> com.ankama.dofus.server.game.protocol.element.LockableCodeResultEvent.LockableResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_game_element_proto_init() }
func file_proto_game_element_proto_init() {
	if File_proto_game_element_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_element_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LockableUseCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_element_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LockableChangeCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_element_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PurchasableDialogEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_element_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LockableShowCodeDialogEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_element_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LockableCodeResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_element_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LockableStateUpdateHouseDoorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_element_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_element_proto_goTypes,
		DependencyIndexes: file_proto_game_element_proto_depIdxs,
		EnumInfos:         file_proto_game_element_proto_enumTypes,
		MessageInfos:      file_proto_game_element_proto_msgTypes,
	}.Build()
	File_proto_game_element_proto = out.File
	file_proto_game_element_proto_rawDesc = nil
	file_proto_game_element_proto_goTypes = nil
	file_proto_game_element_proto_depIdxs = nil
}
