// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/guild_application.proto

package guild_application

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildApplicationSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyText                  string `protobuf:"bytes,1,opt,name=apply_text,json=applyText,proto3" json:"apply_text,omitempty"`
	GuildId                    int32  `protobuf:"varint,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	TimeSpent                  int32  `protobuf:"varint,3,opt,name=time_spent,json=timeSpent,proto3" json:"time_spent,omitempty"`
	LanguageFilter             string `protobuf:"bytes,4,opt,name=language_filter,json=languageFilter,proto3" json:"language_filter,omitempty"`
	AmbianceFilter             string `protobuf:"bytes,5,opt,name=ambiance_filter,json=ambianceFilter,proto3" json:"ambiance_filter,omitempty"`
	PlayTimeFilter             string `protobuf:"bytes,6,opt,name=play_time_filter,json=playTimeFilter,proto3" json:"play_time_filter,omitempty"`
	InterestFilter             string `protobuf:"bytes,7,opt,name=interest_filter,json=interestFilter,proto3" json:"interest_filter,omitempty"`
	MinMaxGuildLevelFilter     string `protobuf:"bytes,8,opt,name=min_max_guild_level_filter,json=minMaxGuildLevelFilter,proto3" json:"min_max_guild_level_filter,omitempty"`
	RecruitmentTypeFilter      string `protobuf:"bytes,9,opt,name=recruitment_type_filter,json=recruitmentTypeFilter,proto3" json:"recruitment_type_filter,omitempty"`
	MinMaxCharacterLevelFilter string `protobuf:"bytes,10,opt,name=min_max_character_level_filter,json=minMaxCharacterLevelFilter,proto3" json:"min_max_character_level_filter,omitempty"`
	MinMaxAchievementFilter    string `protobuf:"bytes,11,opt,name=min_max_achievement_filter,json=minMaxAchievementFilter,proto3" json:"min_max_achievement_filter,omitempty"`
	SearchNameFilter           string `protobuf:"bytes,12,opt,name=search_name_filter,json=searchNameFilter,proto3" json:"search_name_filter,omitempty"`
	LastSortFilter             string `protobuf:"bytes,13,opt,name=last_sort_filter,json=lastSortFilter,proto3" json:"last_sort_filter,omitempty"`
}

func (x *GuildApplicationSubmitRequest) Reset() {
	*x = GuildApplicationSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationSubmitRequest) ProtoMessage() {}

func (x *GuildApplicationSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationSubmitRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationSubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{0}
}

func (x *GuildApplicationSubmitRequest) GetApplyText() string {
	if x != nil {
		return x.ApplyText
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetGuildId() int32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildApplicationSubmitRequest) GetTimeSpent() int32 {
	if x != nil {
		return x.TimeSpent
	}
	return 0
}

func (x *GuildApplicationSubmitRequest) GetLanguageFilter() string {
	if x != nil {
		return x.LanguageFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetAmbianceFilter() string {
	if x != nil {
		return x.AmbianceFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetPlayTimeFilter() string {
	if x != nil {
		return x.PlayTimeFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetInterestFilter() string {
	if x != nil {
		return x.InterestFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetMinMaxGuildLevelFilter() string {
	if x != nil {
		return x.MinMaxGuildLevelFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetRecruitmentTypeFilter() string {
	if x != nil {
		return x.RecruitmentTypeFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetMinMaxCharacterLevelFilter() string {
	if x != nil {
		return x.MinMaxCharacterLevelFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetMinMaxAchievementFilter() string {
	if x != nil {
		return x.MinMaxAchievementFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetSearchNameFilter() string {
	if x != nil {
		return x.SearchNameFilter
	}
	return ""
}

func (x *GuildApplicationSubmitRequest) GetLastSortFilter() string {
	if x != nil {
		return x.LastSortFilter
	}
	return ""
}

type GuildApplicationUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyText string `protobuf:"bytes,1,opt,name=apply_text,json=applyText,proto3" json:"apply_text,omitempty"`
	GuildId   int32  `protobuf:"varint,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *GuildApplicationUpdateRequest) Reset() {
	*x = GuildApplicationUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationUpdateRequest) ProtoMessage() {}

func (x *GuildApplicationUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationUpdateRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{1}
}

func (x *GuildApplicationUpdateRequest) GetApplyText() string {
	if x != nil {
		return x.ApplyText
	}
	return ""
}

func (x *GuildApplicationUpdateRequest) GetGuildId() int32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type GuildApplicationDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuildApplicationDeleteRequest) Reset() {
	*x = GuildApplicationDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationDeleteRequest) ProtoMessage() {}

func (x *GuildApplicationDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationDeleteRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{2}
}

type GuildApplicationListenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listen bool `protobuf:"varint,1,opt,name=listen,proto3" json:"listen,omitempty"`
}

func (x *GuildApplicationListenRequest) Reset() {
	*x = GuildApplicationListenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationListenRequest) ProtoMessage() {}

func (x *GuildApplicationListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationListenRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationListenRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{3}
}

func (x *GuildApplicationListenRequest) GetListen() bool {
	if x != nil {
		return x.Listen
	}
	return false
}

type GuildApplicationGetOwnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuildApplicationGetOwnRequest) Reset() {
	*x = GuildApplicationGetOwnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationGetOwnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationGetOwnRequest) ProtoMessage() {}

func (x *GuildApplicationGetOwnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationGetOwnRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationGetOwnRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{4}
}

type GuildApplicationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GuildApplicationsRequest) Reset() {
	*x = GuildApplicationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationsRequest) ProtoMessage() {}

func (x *GuildApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{5}
}

func (x *GuildApplicationsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GuildApplicationsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GuildApplicationAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	PlayerId int64 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *GuildApplicationAnswerRequest) Reset() {
	*x = GuildApplicationAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationAnswerRequest) ProtoMessage() {}

func (x *GuildApplicationAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationAnswerRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{6}
}

func (x *GuildApplicationAnswerRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GuildApplicationAnswerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GuildApplicationPresenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuildApplicationPresenceRequest) Reset() {
	*x = GuildApplicationPresenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationPresenceRequest) ProtoMessage() {}

func (x *GuildApplicationPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationPresenceRequest.ProtoReflect.Descriptor instead.
func (*GuildApplicationPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{7}
}

type GuildApplicationDeletedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *GuildApplicationDeletedEvent) Reset() {
	*x = GuildApplicationDeletedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationDeletedEvent) ProtoMessage() {}

func (x *GuildApplicationDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationDeletedEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationDeletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{8}
}

func (x *GuildApplicationDeletedEvent) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GuildApplicationPlayerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application *GuildApplicationPlayerEvent_ApplicationInformation `protobuf:"bytes,1,opt,name=application,proto3,oneof" json:"application,omitempty"`
}

func (x *GuildApplicationPlayerEvent) Reset() {
	*x = GuildApplicationPlayerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationPlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationPlayerEvent) ProtoMessage() {}

func (x *GuildApplicationPlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationPlayerEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationPlayerEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{9}
}

func (x *GuildApplicationPlayerEvent) GetApplication() *GuildApplicationPlayerEvent_ApplicationInformation {
	if x != nil {
		return x.Application
	}
	return nil
}

type GuildApplicationAnswerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted         bool                     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	GuildInformation *common.GuildInformation `protobuf:"bytes,2,opt,name=guild_information,json=guildInformation,proto3" json:"guild_information,omitempty"`
}

func (x *GuildApplicationAnswerEvent) Reset() {
	*x = GuildApplicationAnswerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationAnswerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationAnswerEvent) ProtoMessage() {}

func (x *GuildApplicationAnswerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationAnswerEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationAnswerEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{10}
}

func (x *GuildApplicationAnswerEvent) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GuildApplicationAnswerEvent) GetGuildInformation() *common.GuildInformation {
	if x != nil {
		return x.GuildInformation
	}
	return nil
}

type GuildApplicationsEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset  int64                                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count   int64                                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total   int64                                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Applies []*common.SocialApplicationInformation `protobuf:"bytes,4,rep,name=applies,proto3" json:"applies,omitempty"`
}

func (x *GuildApplicationsEvent) Reset() {
	*x = GuildApplicationsEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationsEvent) ProtoMessage() {}

func (x *GuildApplicationsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationsEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationsEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{11}
}

func (x *GuildApplicationsEvent) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GuildApplicationsEvent) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GuildApplicationsEvent) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GuildApplicationsEvent) GetApplies() []*common.SocialApplicationInformation {
	if x != nil {
		return x.Applies
	}
	return nil
}

type GuildApplicationModifiedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application *common.SocialApplicationInformation `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	State       common.SocialApplicationState        `protobuf:"varint,2,opt,name=state,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialApplicationState" json:"state,omitempty"`
	PlayerId    int64                                `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *GuildApplicationModifiedEvent) Reset() {
	*x = GuildApplicationModifiedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationModifiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationModifiedEvent) ProtoMessage() {}

func (x *GuildApplicationModifiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationModifiedEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationModifiedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{12}
}

func (x *GuildApplicationModifiedEvent) GetApplication() *common.SocialApplicationInformation {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *GuildApplicationModifiedEvent) GetState() common.SocialApplicationState {
	if x != nil {
		return x.State
	}
	return common.SocialApplicationState(0)
}

func (x *GuildApplicationModifiedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GuildApplicationReceivedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerId   int64  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *GuildApplicationReceivedEvent) Reset() {
	*x = GuildApplicationReceivedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationReceivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationReceivedEvent) ProtoMessage() {}

func (x *GuildApplicationReceivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationReceivedEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationReceivedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{13}
}

func (x *GuildApplicationReceivedEvent) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *GuildApplicationReceivedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GuildApplicationPresenceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsApplication bool `protobuf:"varint,1,opt,name=is_application,json=isApplication,proto3" json:"is_application,omitempty"`
}

func (x *GuildApplicationPresenceEvent) Reset() {
	*x = GuildApplicationPresenceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationPresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationPresenceEvent) ProtoMessage() {}

func (x *GuildApplicationPresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationPresenceEvent.ProtoReflect.Descriptor instead.
func (*GuildApplicationPresenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{14}
}

func (x *GuildApplicationPresenceEvent) GetIsApplication() bool {
	if x != nil {
		return x.IsApplication
	}
	return false
}

type GuildApplicationPlayerEvent_ApplicationInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildInformation *common.GuildInformation             `protobuf:"bytes,1,opt,name=guild_information,json=guildInformation,proto3" json:"guild_information,omitempty"`
	Apply            *common.SocialApplicationInformation `protobuf:"bytes,2,opt,name=apply,proto3" json:"apply,omitempty"`
}

func (x *GuildApplicationPlayerEvent_ApplicationInformation) Reset() {
	*x = GuildApplicationPlayerEvent_ApplicationInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_guild_application_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplicationPlayerEvent_ApplicationInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationPlayerEvent_ApplicationInformation) ProtoMessage() {}

func (x *GuildApplicationPlayerEvent_ApplicationInformation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_guild_application_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationPlayerEvent_ApplicationInformation.ProtoReflect.Descriptor instead.
func (*GuildApplicationPlayerEvent_ApplicationInformation) Descriptor() ([]byte, []int) {
	return file_proto_game_guild_application_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GuildApplicationPlayerEvent_ApplicationInformation) GetGuildInformation() *common.GuildInformation {
	if x != nil {
		return x.GuildInformation
	}
	return nil
}

func (x *GuildApplicationPlayerEvent_ApplicationInformation) GetApply() *common.SocialApplicationInformation {
	if x != nil {
		return x.Apply
	}
	return nil
}

var File_proto_game_guild_application_proto protoreflect.FileDescriptor

var file_proto_game_guild_application_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x37, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x04, 0x0a, 0x1d,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x6d, 0x62, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6d, 0x62, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x1a, 0x6d,
	0x69, 0x6e, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x16, 0x6d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x1e, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x6d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x1a, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x61,
	0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x6d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x41,
	0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x2c, 0x0a, 0x12, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70,
	0x6c, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x22, 0x1f, 0x0a,
	0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48,
	0x0a, 0x18, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x1c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0xac, 0x03, 0x0a, 0x1b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x92, 0x01, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x6b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61,
	0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x1a, 0xe7, 0x01, 0x0a, 0x16, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x6b, 0x0a, 0x11, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x60, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa6,
	0x01, 0x0a, 0x1b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x6b, 0x0a, 0x11, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61,
	0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x01, 0x0a, 0x16, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x64, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e,
	0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x86, 0x02, 0x0a,
	0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x6c,
	0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x44, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69,
	0x73, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x45, 0x5a, 0x43,
	0x67, 0x6f, 0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2f, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_guild_application_proto_rawDescOnce sync.Once
	file_proto_game_guild_application_proto_rawDescData = file_proto_game_guild_application_proto_rawDesc
)

func file_proto_game_guild_application_proto_rawDescGZIP() []byte {
	file_proto_game_guild_application_proto_rawDescOnce.Do(func() {
		file_proto_game_guild_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_guild_application_proto_rawDescData)
	})
	return file_proto_game_guild_application_proto_rawDescData
}

var file_proto_game_guild_application_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_game_guild_application_proto_goTypes = []any{
	(*GuildApplicationSubmitRequest)(nil),                      // 0: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationSubmitRequest
	(*GuildApplicationUpdateRequest)(nil),                      // 1: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationUpdateRequest
	(*GuildApplicationDeleteRequest)(nil),                      // 2: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationDeleteRequest
	(*GuildApplicationListenRequest)(nil),                      // 3: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationListenRequest
	(*GuildApplicationGetOwnRequest)(nil),                      // 4: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationGetOwnRequest
	(*GuildApplicationsRequest)(nil),                           // 5: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationsRequest
	(*GuildApplicationAnswerRequest)(nil),                      // 6: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationAnswerRequest
	(*GuildApplicationPresenceRequest)(nil),                    // 7: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPresenceRequest
	(*GuildApplicationDeletedEvent)(nil),                       // 8: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationDeletedEvent
	(*GuildApplicationPlayerEvent)(nil),                        // 9: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent
	(*GuildApplicationAnswerEvent)(nil),                        // 10: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationAnswerEvent
	(*GuildApplicationsEvent)(nil),                             // 11: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationsEvent
	(*GuildApplicationModifiedEvent)(nil),                      // 12: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationModifiedEvent
	(*GuildApplicationReceivedEvent)(nil),                      // 13: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationReceivedEvent
	(*GuildApplicationPresenceEvent)(nil),                      // 14: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPresenceEvent
	(*GuildApplicationPlayerEvent_ApplicationInformation)(nil), // 15: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent.ApplicationInformation
	(*common.GuildInformation)(nil),                            // 16: com.ankama.dofus.server.game.protocol.common.GuildInformation
	(*common.SocialApplicationInformation)(nil),                // 17: com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	(common.SocialApplicationState)(0),                         // 18: com.ankama.dofus.server.game.protocol.common.SocialApplicationState
}
var file_proto_game_guild_application_proto_depIdxs = []int32{
	15, // 0: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent.application:type_name -> com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent.ApplicationInformation
	16, // 1: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationAnswerEvent.guild_information:type_name -> com.ankama.dofus.server.game.protocol.common.GuildInformation
	17, // 2: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationsEvent.applies:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	17, // 3: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationModifiedEvent.application:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	18, // 4: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationModifiedEvent.state:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationState
	16, // 5: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent.ApplicationInformation.guild_information:type_name -> com.ankama.dofus.server.game.protocol.common.GuildInformation
	17, // 6: com.ankama.dofus.server.game.protocol.guild.application.GuildApplicationPlayerEvent.ApplicationInformation.apply:type_name -> com.ankama.dofus.server.game.protocol.common.SocialApplicationInformation
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_game_guild_application_proto_init() }
func file_proto_game_guild_application_proto_init() {
	if File_proto_game_guild_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_guild_application_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationListenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationGetOwnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationPresenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationDeletedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationPlayerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationAnswerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationsEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationModifiedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationReceivedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationPresenceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_guild_application_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GuildApplicationPlayerEvent_ApplicationInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_game_guild_application_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_guild_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_guild_application_proto_goTypes,
		DependencyIndexes: file_proto_game_guild_application_proto_depIdxs,
		MessageInfos:      file_proto_game_guild_application_proto_msgTypes,
	}.Build()
	File_proto_game_guild_application_proto = out.File
	file_proto_game_guild_application_proto_rawDesc = nil
	file_proto_game_guild_application_proto_goTypes = nil
	file_proto_game_guild_application_proto_depIdxs = nil
}
