// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/living_object.proto

package living_object

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LivingObjectMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId int32 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ObjectGid int32 `protobuf:"varint,2,opt,name=object_gid,json=objectGid,proto3" json:"object_gid,omitempty"`
}

func (x *LivingObjectMessageRequest) Reset() {
	*x = LivingObjectMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_living_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivingObjectMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivingObjectMessageRequest) ProtoMessage() {}

func (x *LivingObjectMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_living_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivingObjectMessageRequest.ProtoReflect.Descriptor instead.
func (*LivingObjectMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_living_object_proto_rawDescGZIP(), []int{0}
}

func (x *LivingObjectMessageRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LivingObjectMessageRequest) GetObjectGid() int32 {
	if x != nil {
		return x.ObjectGid
	}
	return 0
}

type LivingObjectDissociateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectUid int32 `protobuf:"varint,1,opt,name=object_uid,json=objectUid,proto3" json:"object_uid,omitempty"`
	Position  int32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *LivingObjectDissociateRequest) Reset() {
	*x = LivingObjectDissociateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_living_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivingObjectDissociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivingObjectDissociateRequest) ProtoMessage() {}

func (x *LivingObjectDissociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_living_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivingObjectDissociateRequest.ProtoReflect.Descriptor instead.
func (*LivingObjectDissociateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_living_object_proto_rawDescGZIP(), []int{1}
}

func (x *LivingObjectDissociateRequest) GetObjectUid() int32 {
	if x != nil {
		return x.ObjectUid
	}
	return 0
}

func (x *LivingObjectDissociateRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type LivingObjectChangeSkinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectUid int32 `protobuf:"varint,1,opt,name=object_uid,json=objectUid,proto3" json:"object_uid,omitempty"`
	Position  int32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	SkinId    int32 `protobuf:"varint,3,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
}

func (x *LivingObjectChangeSkinRequest) Reset() {
	*x = LivingObjectChangeSkinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_living_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivingObjectChangeSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivingObjectChangeSkinRequest) ProtoMessage() {}

func (x *LivingObjectChangeSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_living_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivingObjectChangeSkinRequest.ProtoReflect.Descriptor instead.
func (*LivingObjectChangeSkinRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_living_object_proto_rawDescGZIP(), []int{2}
}

func (x *LivingObjectChangeSkinRequest) GetObjectUid() int32 {
	if x != nil {
		return x.ObjectUid
	}
	return 0
}

func (x *LivingObjectChangeSkinRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *LivingObjectChangeSkinRequest) GetSkinId() int32 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

type LivingObjectMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId int32  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OwnerName string `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	ObjectGid int32  `protobuf:"varint,4,opt,name=object_gid,json=objectGid,proto3" json:"object_gid,omitempty"`
}

func (x *LivingObjectMessageEvent) Reset() {
	*x = LivingObjectMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_living_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivingObjectMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivingObjectMessageEvent) ProtoMessage() {}

func (x *LivingObjectMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_living_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivingObjectMessageEvent.ProtoReflect.Descriptor instead.
func (*LivingObjectMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_living_object_proto_rawDescGZIP(), []int{3}
}

func (x *LivingObjectMessageEvent) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LivingObjectMessageEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LivingObjectMessageEvent) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *LivingObjectMessageEvent) GetObjectGid() int32 {
	if x != nil {
		return x.ObjectGid
	}
	return 0
}

var File_proto_game_living_object_proto protoreflect.FileDescriptor

var file_proto_game_living_object_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6c, 0x69, 0x76,
	0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x33, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66,
	0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x6c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x2e, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x5a, 0x0a, 0x1a, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x67, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x69,
	0x64, 0x22, 0x5a, 0x0a, 0x1d, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a,
	0x1d, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6b, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x69, 0x64, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x6f,
	0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x6c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_living_object_proto_rawDescOnce sync.Once
	file_proto_game_living_object_proto_rawDescData = file_proto_game_living_object_proto_rawDesc
)

func file_proto_game_living_object_proto_rawDescGZIP() []byte {
	file_proto_game_living_object_proto_rawDescOnce.Do(func() {
		file_proto_game_living_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_living_object_proto_rawDescData)
	})
	return file_proto_game_living_object_proto_rawDescData
}

var file_proto_game_living_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_game_living_object_proto_goTypes = []any{
	(*LivingObjectMessageRequest)(nil),    // 0: com.ankama.dofus.server.game.protocol.living.object.LivingObjectMessageRequest
	(*LivingObjectDissociateRequest)(nil), // 1: com.ankama.dofus.server.game.protocol.living.object.LivingObjectDissociateRequest
	(*LivingObjectChangeSkinRequest)(nil), // 2: com.ankama.dofus.server.game.protocol.living.object.LivingObjectChangeSkinRequest
	(*LivingObjectMessageEvent)(nil),      // 3: com.ankama.dofus.server.game.protocol.living.object.LivingObjectMessageEvent
}
var file_proto_game_living_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_game_living_object_proto_init() }
func file_proto_game_living_object_proto_init() {
	if File_proto_game_living_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_living_object_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LivingObjectMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_living_object_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LivingObjectDissociateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_living_object_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LivingObjectChangeSkinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_living_object_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LivingObjectMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_living_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_living_object_proto_goTypes,
		DependencyIndexes: file_proto_game_living_object_proto_depIdxs,
		MessageInfos:      file_proto_game_living_object_proto_msgTypes,
	}.Build()
	File_proto_game_living_object_proto = out.File
	file_proto_game_living_object_proto_rawDesc = nil
	file_proto_game_living_object_proto_goTypes = nil
	file_proto_game_living_object_proto_depIdxs = nil
}
