// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/alliance_information.proto

package alliance_information

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllianceSummaryRequest_DirectoryTextFilter int32

const (
	AllianceSummaryRequest_ALLIANCE_SEARCH_DEFAULT_FILTER AllianceSummaryRequest_DirectoryTextFilter = 0
	AllianceSummaryRequest_ALLIANCE_SEARCH_NAME_FILTER    AllianceSummaryRequest_DirectoryTextFilter = 1
	AllianceSummaryRequest_ALLIANCE_SEARCH_TAG_FILTER     AllianceSummaryRequest_DirectoryTextFilter = 2
)

// Enum value maps for AllianceSummaryRequest_DirectoryTextFilter.
var (
	AllianceSummaryRequest_DirectoryTextFilter_name = map[int32]string{
		0: "ALLIANCE_SEARCH_DEFAULT_FILTER",
		1: "ALLIANCE_SEARCH_NAME_FILTER",
		2: "ALLIANCE_SEARCH_TAG_FILTER",
	}
	AllianceSummaryRequest_DirectoryTextFilter_value = map[string]int32{
		"ALLIANCE_SEARCH_DEFAULT_FILTER": 0,
		"ALLIANCE_SEARCH_NAME_FILTER":    1,
		"ALLIANCE_SEARCH_TAG_FILTER":     2,
	}
)

func (x AllianceSummaryRequest_DirectoryTextFilter) Enum() *AllianceSummaryRequest_DirectoryTextFilter {
	p := new(AllianceSummaryRequest_DirectoryTextFilter)
	*p = x
	return p
}

func (x AllianceSummaryRequest_DirectoryTextFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllianceSummaryRequest_DirectoryTextFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_alliance_information_proto_enumTypes[0].Descriptor()
}

func (AllianceSummaryRequest_DirectoryTextFilter) Type() protoreflect.EnumType {
	return &file_proto_game_alliance_information_proto_enumTypes[0]
}

func (x AllianceSummaryRequest_DirectoryTextFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllianceSummaryRequest_DirectoryTextFilter.Descriptor instead.
func (AllianceSummaryRequest_DirectoryTextFilter) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{12, 0}
}

type AllianceSummaryRequest_AllianceSummarySort int32

const (
	AllianceSummaryRequest_SORT_BY_ALLIANCE_NAME       AllianceSummaryRequest_AllianceSummarySort = 0
	AllianceSummaryRequest_SORT_BY_ALLIANCE_TAG        AllianceSummaryRequest_AllianceSummarySort = 1
	AllianceSummaryRequest_SORT_BY_NB_TERRITORIES      AllianceSummaryRequest_AllianceSummarySort = 2
	AllianceSummaryRequest_SORT_BY_ALLIANCE_NB_MEMBERS AllianceSummaryRequest_AllianceSummarySort = 3
)

// Enum value maps for AllianceSummaryRequest_AllianceSummarySort.
var (
	AllianceSummaryRequest_AllianceSummarySort_name = map[int32]string{
		0: "SORT_BY_ALLIANCE_NAME",
		1: "SORT_BY_ALLIANCE_TAG",
		2: "SORT_BY_NB_TERRITORIES",
		3: "SORT_BY_ALLIANCE_NB_MEMBERS",
	}
	AllianceSummaryRequest_AllianceSummarySort_value = map[string]int32{
		"SORT_BY_ALLIANCE_NAME":       0,
		"SORT_BY_ALLIANCE_TAG":        1,
		"SORT_BY_NB_TERRITORIES":      2,
		"SORT_BY_ALLIANCE_NB_MEMBERS": 3,
	}
)

func (x AllianceSummaryRequest_AllianceSummarySort) Enum() *AllianceSummaryRequest_AllianceSummarySort {
	p := new(AllianceSummaryRequest_AllianceSummarySort)
	*p = x
	return p
}

func (x AllianceSummaryRequest_AllianceSummarySort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllianceSummaryRequest_AllianceSummarySort) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_alliance_information_proto_enumTypes[1].Descriptor()
}

func (AllianceSummaryRequest_AllianceSummarySort) Type() protoreflect.EnumType {
	return &file_proto_game_alliance_information_proto_enumTypes[1]
}

func (x AllianceSummaryRequest_AllianceSummarySort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllianceSummaryRequest_AllianceSummarySort.Descriptor instead.
func (AllianceSummaryRequest_AllianceSummarySort) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{12, 1}
}

type AllianceCreationValidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceName   string               `protobuf:"bytes,1,opt,name=alliance_name,json=allianceName,proto3" json:"alliance_name,omitempty"`
	AllianceTag    string               `protobuf:"bytes,2,opt,name=alliance_tag,json=allianceTag,proto3" json:"alliance_tag,omitempty"`
	AllianceEmblem *common.SocialEmblem `protobuf:"bytes,3,opt,name=alliance_emblem,json=allianceEmblem,proto3" json:"alliance_emblem,omitempty"`
}

func (x *AllianceCreationValidRequest) Reset() {
	*x = AllianceCreationValidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceCreationValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceCreationValidRequest) ProtoMessage() {}

func (x *AllianceCreationValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceCreationValidRequest.ProtoReflect.Descriptor instead.
func (*AllianceCreationValidRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{0}
}

func (x *AllianceCreationValidRequest) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

func (x *AllianceCreationValidRequest) GetAllianceTag() string {
	if x != nil {
		return x.AllianceTag
	}
	return ""
}

func (x *AllianceCreationValidRequest) GetAllianceEmblem() *common.SocialEmblem {
	if x != nil {
		return x.AllianceEmblem
	}
	return nil
}

type AllianceEmblemModificationValidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceEmblem *common.SocialEmblem `protobuf:"bytes,1,opt,name=alliance_emblem,json=allianceEmblem,proto3" json:"alliance_emblem,omitempty"`
}

func (x *AllianceEmblemModificationValidRequest) Reset() {
	*x = AllianceEmblemModificationValidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceEmblemModificationValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceEmblemModificationValidRequest) ProtoMessage() {}

func (x *AllianceEmblemModificationValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceEmblemModificationValidRequest.ProtoReflect.Descriptor instead.
func (*AllianceEmblemModificationValidRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{1}
}

func (x *AllianceEmblemModificationValidRequest) GetAllianceEmblem() *common.SocialEmblem {
	if x != nil {
		return x.AllianceEmblem
	}
	return nil
}

type AllianceNameAndTagModificationValidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceName string `protobuf:"bytes,1,opt,name=alliance_name,json=allianceName,proto3" json:"alliance_name,omitempty"`
	AllianceTag  string `protobuf:"bytes,2,opt,name=alliance_tag,json=allianceTag,proto3" json:"alliance_tag,omitempty"`
}

func (x *AllianceNameAndTagModificationValidRequest) Reset() {
	*x = AllianceNameAndTagModificationValidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceNameAndTagModificationValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceNameAndTagModificationValidRequest) ProtoMessage() {}

func (x *AllianceNameAndTagModificationValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceNameAndTagModificationValidRequest.ProtoReflect.Descriptor instead.
func (*AllianceNameAndTagModificationValidRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{2}
}

func (x *AllianceNameAndTagModificationValidRequest) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

func (x *AllianceNameAndTagModificationValidRequest) GetAllianceTag() string {
	if x != nil {
		return x.AllianceTag
	}
	return ""
}

type AllianceModificationValidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceName   string               `protobuf:"bytes,1,opt,name=alliance_name,json=allianceName,proto3" json:"alliance_name,omitempty"`
	AllianceTag    string               `protobuf:"bytes,2,opt,name=alliance_tag,json=allianceTag,proto3" json:"alliance_tag,omitempty"`
	AllianceEmblem *common.SocialEmblem `protobuf:"bytes,3,opt,name=alliance_emblem,json=allianceEmblem,proto3" json:"alliance_emblem,omitempty"`
}

func (x *AllianceModificationValidRequest) Reset() {
	*x = AllianceModificationValidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceModificationValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceModificationValidRequest) ProtoMessage() {}

func (x *AllianceModificationValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceModificationValidRequest.ProtoReflect.Descriptor instead.
func (*AllianceModificationValidRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{3}
}

func (x *AllianceModificationValidRequest) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

func (x *AllianceModificationValidRequest) GetAllianceTag() string {
	if x != nil {
		return x.AllianceTag
	}
	return ""
}

func (x *AllianceModificationValidRequest) GetAllianceEmblem() *common.SocialEmblem {
	if x != nil {
		return x.AllianceEmblem
	}
	return nil
}

type AllianceMemberStartWarningOnConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceMemberStartWarningOnConnectionRequest) Reset() {
	*x = AllianceMemberStartWarningOnConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMemberStartWarningOnConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMemberStartWarningOnConnectionRequest) ProtoMessage() {}

func (x *AllianceMemberStartWarningOnConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMemberStartWarningOnConnectionRequest.ProtoReflect.Descriptor instead.
func (*AllianceMemberStartWarningOnConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{4}
}

type AllianceMemberStopWarningOnConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceMemberStopWarningOnConnectionRequest) Reset() {
	*x = AllianceMemberStopWarningOnConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMemberStopWarningOnConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMemberStopWarningOnConnectionRequest) ProtoMessage() {}

func (x *AllianceMemberStopWarningOnConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMemberStopWarningOnConnectionRequest.ProtoReflect.Descriptor instead.
func (*AllianceMemberStopWarningOnConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{5}
}

type AllianceCreationStartedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceCreationStartedEvent) Reset() {
	*x = AllianceCreationStartedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceCreationStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceCreationStartedEvent) ProtoMessage() {}

func (x *AllianceCreationStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceCreationStartedEvent.ProtoReflect.Descriptor instead.
func (*AllianceCreationStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{6}
}

type AllianceModificationStartedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanChangeName   bool `protobuf:"varint,1,opt,name=can_change_name,json=canChangeName,proto3" json:"can_change_name,omitempty"`
	CanChangeTag    bool `protobuf:"varint,2,opt,name=can_change_tag,json=canChangeTag,proto3" json:"can_change_tag,omitempty"`
	CanChangeEmblem bool `protobuf:"varint,3,opt,name=can_change_emblem,json=canChangeEmblem,proto3" json:"can_change_emblem,omitempty"`
}

func (x *AllianceModificationStartedEvent) Reset() {
	*x = AllianceModificationStartedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceModificationStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceModificationStartedEvent) ProtoMessage() {}

func (x *AllianceModificationStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceModificationStartedEvent.ProtoReflect.Descriptor instead.
func (*AllianceModificationStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{7}
}

func (x *AllianceModificationStartedEvent) GetCanChangeName() bool {
	if x != nil {
		return x.CanChangeName
	}
	return false
}

func (x *AllianceModificationStartedEvent) GetCanChangeTag() bool {
	if x != nil {
		return x.CanChangeTag
	}
	return false
}

func (x *AllianceModificationStartedEvent) GetCanChangeEmblem() bool {
	if x != nil {
		return x.CanChangeEmblem
	}
	return false
}

type AllianceCreationResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result common.SocialGroupOperationResult `protobuf:"varint,1,opt,name=result,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialGroupOperationResult" json:"result,omitempty"`
}

func (x *AllianceCreationResultEvent) Reset() {
	*x = AllianceCreationResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceCreationResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceCreationResultEvent) ProtoMessage() {}

func (x *AllianceCreationResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceCreationResultEvent.ProtoReflect.Descriptor instead.
func (*AllianceCreationResultEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{8}
}

func (x *AllianceCreationResultEvent) GetResult() common.SocialGroupOperationResult {
	if x != nil {
		return x.Result
	}
	return common.SocialGroupOperationResult(0)
}

type AllianceModificationResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result common.SocialGroupOperationResult `protobuf:"varint,1,opt,name=result,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialGroupOperationResult" json:"result,omitempty"`
}

func (x *AllianceModificationResultEvent) Reset() {
	*x = AllianceModificationResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceModificationResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceModificationResultEvent) ProtoMessage() {}

func (x *AllianceModificationResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceModificationResultEvent.ProtoReflect.Descriptor instead.
func (*AllianceModificationResultEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{9}
}

func (x *AllianceModificationResultEvent) GetResult() common.SocialGroupOperationResult {
	if x != nil {
		return x.Result
	}
	return common.SocialGroupOperationResult(0)
}

type AllianceInsiderInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllianceInsiderInformationRequest) Reset() {
	*x = AllianceInsiderInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceInsiderInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceInsiderInformationRequest) ProtoMessage() {}

func (x *AllianceInsiderInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceInsiderInformationRequest.ProtoReflect.Descriptor instead.
func (*AllianceInsiderInformationRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{10}
}

type AllianceFactsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceUuid string `protobuf:"bytes,1,opt,name=alliance_uuid,json=allianceUuid,proto3" json:"alliance_uuid,omitempty"`
}

func (x *AllianceFactsRequest) Reset() {
	*x = AllianceFactsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceFactsRequest) ProtoMessage() {}

func (x *AllianceFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceFactsRequest.ProtoReflect.Descriptor instead.
func (*AllianceFactsRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{11}
}

func (x *AllianceFactsRequest) GetAllianceUuid() string {
	if x != nil {
		return x.AllianceUuid
	}
	return ""
}

type AllianceSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset                    int64                                      `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                     int64                                      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	FilterType                AllianceSummaryRequest_DirectoryTextFilter `protobuf:"varint,3,opt,name=filter_type,json=filterType,proto3,enum=com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest_DirectoryTextFilter" json:"filter_type,omitempty"`
	TextFiler                 string                                     `protobuf:"bytes,4,opt,name=text_filer,json=textFiler,proto3" json:"text_filer,omitempty"`
	HideFullFilter            bool                                       `protobuf:"varint,5,opt,name=hide_full_filter,json=hideFullFilter,proto3" json:"hide_full_filter,omitempty"`
	FollowingAllianceCriteria bool                                       `protobuf:"varint,6,opt,name=following_alliance_criteria,json=followingAllianceCriteria,proto3" json:"following_alliance_criteria,omitempty"`
	CriterionFilter           []int32                                    `protobuf:"varint,7,rep,packed,name=criterion_filter,json=criterionFilter,proto3" json:"criterion_filter,omitempty"`
	SortType                  AllianceSummaryRequest_AllianceSummarySort `protobuf:"varint,8,opt,name=sort_type,json=sortType,proto3,enum=com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest_AllianceSummarySort" json:"sort_type,omitempty"`
	SortDescending            bool                                       `protobuf:"varint,9,opt,name=sort_descending,json=sortDescending,proto3" json:"sort_descending,omitempty"`
	LanguagesFilter           []int32                                    `protobuf:"varint,10,rep,packed,name=languages_filter,json=languagesFilter,proto3" json:"languages_filter,omitempty"`
	RecruitmentTypeFilter     []common.SocialRecruitmentType             `protobuf:"varint,11,rep,packed,name=recruitment_type_filter,json=recruitmentTypeFilter,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialRecruitmentType" json:"recruitment_type_filter,omitempty"`
	MinPlayerLevelFilter      int32                                      `protobuf:"varint,12,opt,name=min_player_level_filter,json=minPlayerLevelFilter,proto3" json:"min_player_level_filter,omitempty"`
	MaxPlayerLevelFilter      int32                                      `protobuf:"varint,13,opt,name=max_player_level_filter,json=maxPlayerLevelFilter,proto3" json:"max_player_level_filter,omitempty"`
}

func (x *AllianceSummaryRequest) Reset() {
	*x = AllianceSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceSummaryRequest) ProtoMessage() {}

func (x *AllianceSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceSummaryRequest.ProtoReflect.Descriptor instead.
func (*AllianceSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{12}
}

func (x *AllianceSummaryRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AllianceSummaryRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AllianceSummaryRequest) GetFilterType() AllianceSummaryRequest_DirectoryTextFilter {
	if x != nil {
		return x.FilterType
	}
	return AllianceSummaryRequest_ALLIANCE_SEARCH_DEFAULT_FILTER
}

func (x *AllianceSummaryRequest) GetTextFiler() string {
	if x != nil {
		return x.TextFiler
	}
	return ""
}

func (x *AllianceSummaryRequest) GetHideFullFilter() bool {
	if x != nil {
		return x.HideFullFilter
	}
	return false
}

func (x *AllianceSummaryRequest) GetFollowingAllianceCriteria() bool {
	if x != nil {
		return x.FollowingAllianceCriteria
	}
	return false
}

func (x *AllianceSummaryRequest) GetCriterionFilter() []int32 {
	if x != nil {
		return x.CriterionFilter
	}
	return nil
}

func (x *AllianceSummaryRequest) GetSortType() AllianceSummaryRequest_AllianceSummarySort {
	if x != nil {
		return x.SortType
	}
	return AllianceSummaryRequest_SORT_BY_ALLIANCE_NAME
}

func (x *AllianceSummaryRequest) GetSortDescending() bool {
	if x != nil {
		return x.SortDescending
	}
	return false
}

func (x *AllianceSummaryRequest) GetLanguagesFilter() []int32 {
	if x != nil {
		return x.LanguagesFilter
	}
	return nil
}

func (x *AllianceSummaryRequest) GetRecruitmentTypeFilter() []common.SocialRecruitmentType {
	if x != nil {
		return x.RecruitmentTypeFilter
	}
	return nil
}

func (x *AllianceSummaryRequest) GetMinPlayerLevelFilter() int32 {
	if x != nil {
		return x.MinPlayerLevelFilter
	}
	return 0
}

func (x *AllianceSummaryRequest) GetMaxPlayerLevelFilter() int32 {
	if x != nil {
		return x.MaxPlayerLevelFilter
	}
	return 0
}

type AllianceInsiderInformationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Information   *common.AllianceInformation         `protobuf:"bytes,1,opt,name=information,proto3" json:"information,omitempty"`
	Members       []*common.AllianceMemberInformation `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Prisms        []*common.PrismLocalizedInformation `protobuf:"bytes,3,rep,name=prisms,proto3" json:"prisms,omitempty"`
	TaxCollectors []*common.TaxCollectorInformation   `protobuf:"bytes,4,rep,name=tax_collectors,json=taxCollectors,proto3" json:"tax_collectors,omitempty"`
}

func (x *AllianceInsiderInformationEvent) Reset() {
	*x = AllianceInsiderInformationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceInsiderInformationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceInsiderInformationEvent) ProtoMessage() {}

func (x *AllianceInsiderInformationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceInsiderInformationEvent.ProtoReflect.Descriptor instead.
func (*AllianceInsiderInformationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{13}
}

func (x *AllianceInsiderInformationEvent) GetInformation() *common.AllianceInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

func (x *AllianceInsiderInformationEvent) GetMembers() []*common.AllianceMemberInformation {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *AllianceInsiderInformationEvent) GetPrisms() []*common.PrismLocalizedInformation {
	if x != nil {
		return x.Prisms
	}
	return nil
}

func (x *AllianceInsiderInformationEvent) GetTaxCollectors() []*common.TaxCollectorInformation {
	if x != nil {
		return x.TaxCollectors
	}
	return nil
}

type AllianceFactsErrorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceUuid string `protobuf:"bytes,1,opt,name=alliance_uuid,json=allianceUuid,proto3" json:"alliance_uuid,omitempty"`
}

func (x *AllianceFactsErrorEvent) Reset() {
	*x = AllianceFactsErrorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceFactsErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceFactsErrorEvent) ProtoMessage() {}

func (x *AllianceFactsErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceFactsErrorEvent.ProtoReflect.Descriptor instead.
func (*AllianceFactsErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{14}
}

func (x *AllianceFactsErrorEvent) GetAllianceUuid() string {
	if x != nil {
		return x.AllianceUuid
	}
	return ""
}

type AllianceFactsEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceInformation  *common.AllianceInformation `protobuf:"bytes,1,opt,name=alliance_information,json=allianceInformation,proto3" json:"alliance_information,omitempty"`
	Members              []*common.Character         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	ControlledSubareaIds []int32                     `protobuf:"varint,3,rep,packed,name=controlled_subarea_ids,json=controlledSubareaIds,proto3" json:"controlled_subarea_ids,omitempty"`
	LeaderId             int64                       `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderName           string                      `protobuf:"bytes,5,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
}

func (x *AllianceFactsEvent) Reset() {
	*x = AllianceFactsEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceFactsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceFactsEvent) ProtoMessage() {}

func (x *AllianceFactsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceFactsEvent.ProtoReflect.Descriptor instead.
func (*AllianceFactsEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{15}
}

func (x *AllianceFactsEvent) GetAllianceInformation() *common.AllianceInformation {
	if x != nil {
		return x.AllianceInformation
	}
	return nil
}

func (x *AllianceFactsEvent) GetMembers() []*common.Character {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *AllianceFactsEvent) GetControlledSubareaIds() []int32 {
	if x != nil {
		return x.ControlledSubareaIds
	}
	return nil
}

func (x *AllianceFactsEvent) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AllianceFactsEvent) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

type AllianceSummaryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset    int64                         `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count     int64                         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total     int64                         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Alliances []*common.AllianceInformation `protobuf:"bytes,4,rep,name=alliances,proto3" json:"alliances,omitempty"`
}

func (x *AllianceSummaryEvent) Reset() {
	*x = AllianceSummaryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceSummaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceSummaryEvent) ProtoMessage() {}

func (x *AllianceSummaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceSummaryEvent.ProtoReflect.Descriptor instead.
func (*AllianceSummaryEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{16}
}

func (x *AllianceSummaryEvent) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AllianceSummaryEvent) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AllianceSummaryEvent) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AllianceSummaryEvent) GetAlliances() []*common.AllianceInformation {
	if x != nil {
		return x.Alliances
	}
	return nil
}

type AllianceMotdSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AllianceMotdSetRequest) Reset() {
	*x = AllianceMotdSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMotdSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMotdSetRequest) ProtoMessage() {}

func (x *AllianceMotdSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMotdSetRequest.ProtoReflect.Descriptor instead.
func (*AllianceMotdSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{17}
}

func (x *AllianceMotdSetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AllianceMotdEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MotdInfo *common.SocialNoticeInformation `protobuf:"bytes,1,opt,name=motd_info,json=motdInfo,proto3" json:"motd_info,omitempty"`
}

func (x *AllianceMotdEvent) Reset() {
	*x = AllianceMotdEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMotdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMotdEvent) ProtoMessage() {}

func (x *AllianceMotdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMotdEvent.ProtoReflect.Descriptor instead.
func (*AllianceMotdEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{18}
}

func (x *AllianceMotdEvent) GetMotdInfo() *common.SocialNoticeInformation {
	if x != nil {
		return x.MotdInfo
	}
	return nil
}

type AllianceMotdSetErrorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason common.SocialNoticeError `protobuf:"varint,1,opt,name=reason,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialNoticeError" json:"reason,omitempty"`
}

func (x *AllianceMotdSetErrorEvent) Reset() {
	*x = AllianceMotdSetErrorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMotdSetErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMotdSetErrorEvent) ProtoMessage() {}

func (x *AllianceMotdSetErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMotdSetErrorEvent.ProtoReflect.Descriptor instead.
func (*AllianceMotdSetErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{19}
}

func (x *AllianceMotdSetErrorEvent) GetReason() common.SocialNoticeError {
	if x != nil {
		return x.Reason
	}
	return common.SocialNoticeError(0)
}

type AllianceBulletinSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AllianceBulletinSetRequest) Reset() {
	*x = AllianceBulletinSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceBulletinSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceBulletinSetRequest) ProtoMessage() {}

func (x *AllianceBulletinSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceBulletinSetRequest.ProtoReflect.Descriptor instead.
func (*AllianceBulletinSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{20}
}

func (x *AllianceBulletinSetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AllianceBulletinEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BulletinInfo *common.SocialNoticeInformation `protobuf:"bytes,1,opt,name=bulletin_info,json=bulletinInfo,proto3" json:"bulletin_info,omitempty"`
}

func (x *AllianceBulletinEvent) Reset() {
	*x = AllianceBulletinEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceBulletinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceBulletinEvent) ProtoMessage() {}

func (x *AllianceBulletinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceBulletinEvent.ProtoReflect.Descriptor instead.
func (*AllianceBulletinEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{21}
}

func (x *AllianceBulletinEvent) GetBulletinInfo() *common.SocialNoticeInformation {
	if x != nil {
		return x.BulletinInfo
	}
	return nil
}

type AllianceBulletinSetErrorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason common.SocialNoticeError `protobuf:"varint,1,opt,name=reason,proto3,enum=com.ankama.dofus.server.game.protocol.common.SocialNoticeError" json:"reason,omitempty"`
}

func (x *AllianceBulletinSetErrorEvent) Reset() {
	*x = AllianceBulletinSetErrorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_alliance_information_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceBulletinSetErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceBulletinSetErrorEvent) ProtoMessage() {}

func (x *AllianceBulletinSetErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_alliance_information_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceBulletinSetErrorEvent.ProtoReflect.Descriptor instead.
func (*AllianceBulletinSetErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_alliance_information_proto_rawDescGZIP(), []int{22}
}

func (x *AllianceBulletinSetErrorEvent) GetReason() common.SocialNoticeError {
	if x != nil {
		return x.Reason
	}
	return common.SocialNoticeError(0)
}

var File_proto_game_alliance_information_proto protoreflect.FileDescriptor

var file_proto_game_alliance_information_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3a, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b,
	0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x1c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x61, 0x67, 0x12, 0x63, 0x0a, 0x0f, 0x61, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x52,
	0x0e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x22,
	0x8d, 0x01, 0x0a, 0x26, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6d, 0x62, 0x6c,
	0x65, 0x6d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x63, 0x0a, 0x0f, 0x61, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x52,
	0x0e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x22,
	0x74, 0x0a, 0x2a, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x41,
	0x6e, 0x64, 0x54, 0x61, 0x67, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x54, 0x61, 0x67, 0x22, 0xcf, 0x01, 0x0a, 0x20, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x61, 0x67, 0x12, 0x63, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x65,
	0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x22, 0x2f, 0x0a, 0x2d, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x2c, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x20, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a,
	0x0f, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x63,
	0x61, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x67, 0x12, 0x2a, 0x0a, 0x11, 0x63,
	0x61, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x45, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x22, 0x7f, 0x0a, 0x1b, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x60, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x48, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b,
	0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x1f, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x60, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x48, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x23,
	0x0a, 0x21, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x46,
	0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64,
	0x22, 0xcf, 0x08, 0x0a, 0x16, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x87, 0x01, 0x0a, 0x0b, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66,
	0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x65, 0x78,
	0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x69,
	0x64, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x1b,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x19, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x29, 0x0a, 0x10,
	0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f,
	0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x83, 0x01, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x66, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53,
	0x6f, 0x72, 0x74, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x7b, 0x0a, 0x17, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x43, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x15, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x35,
	0x0a, 0x17, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x14, 0x6d, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x17, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x7a, 0x0a, 0x13,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x65, 0x78, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x1e, 0x41, 0x4c, 0x4c, 0x49, 0x41, 0x4e, 0x43, 0x45, 0x5f,
	0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f, 0x46,
	0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x41, 0x4c, 0x4c, 0x49, 0x41,
	0x4e, 0x43, 0x45, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f,
	0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x4c, 0x4c, 0x49,
	0x41, 0x4e, 0x43, 0x45, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x41, 0x47, 0x5f,
	0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x02, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x19, 0x0a, 0x15, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x41, 0x4c, 0x4c, 0x49,
	0x41, 0x4e, 0x43, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53,
	0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x41, 0x4c, 0x4c, 0x49, 0x41, 0x4e, 0x43, 0x45, 0x5f,
	0x54, 0x41, 0x47, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59,
	0x5f, 0x4e, 0x42, 0x5f, 0x54, 0x45, 0x52, 0x52, 0x49, 0x54, 0x4f, 0x52, 0x49, 0x45, 0x53, 0x10,
	0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x41, 0x4c, 0x4c,
	0x49, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x4e, 0x42, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x53,
	0x10, 0x03, 0x22, 0xb8, 0x03, 0x0a, 0x1f, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x63, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x61, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x5f,
	0x0a, 0x06, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x47,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75,
	0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72,
	0x69, 0x73, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x73, 0x12,
	0x6c, 0x0a, 0x0e, 0x74, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e,
	0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x78, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x74, 0x61, 0x78, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x3e, 0x0a,
	0x17, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x61, 0x63, 0x74, 0x73, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0xd1, 0x02,
	0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x61, 0x63, 0x74, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x74, 0x0a, 0x14, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a,
	0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x73, 0x75, 0x62, 0x61,
	0x72, 0x65, 0x61, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x14, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x53, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61,
	0x49, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0xbb, 0x01, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x5f,
	0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64,
	0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22,
	0x32, 0x0a, 0x16, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x74, 0x64, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x77, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d,
	0x6f, 0x74, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x09, 0x6d, 0x6f, 0x74, 0x64,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x6d, 0x6f, 0x74, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x74, 0x0a, 0x19,
	0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x74, 0x64, 0x53, 0x65, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x57, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x1a, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x75,
	0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x41,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x6a, 0x0a, 0x0d, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x78, 0x0a, 0x1d, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x75, 0x6c, 0x6c,
	0x65, 0x74, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x57, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64,
	0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x6f,
	0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_alliance_information_proto_rawDescOnce sync.Once
	file_proto_game_alliance_information_proto_rawDescData = file_proto_game_alliance_information_proto_rawDesc
)

func file_proto_game_alliance_information_proto_rawDescGZIP() []byte {
	file_proto_game_alliance_information_proto_rawDescOnce.Do(func() {
		file_proto_game_alliance_information_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_alliance_information_proto_rawDescData)
	})
	return file_proto_game_alliance_information_proto_rawDescData
}

var file_proto_game_alliance_information_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_game_alliance_information_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_game_alliance_information_proto_goTypes = []any{
	(AllianceSummaryRequest_DirectoryTextFilter)(0),       // 0: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.DirectoryTextFilter
	(AllianceSummaryRequest_AllianceSummarySort)(0),       // 1: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.AllianceSummarySort
	(*AllianceCreationValidRequest)(nil),                  // 2: com.ankama.dofus.server.game.protocol.alliance.information.AllianceCreationValidRequest
	(*AllianceEmblemModificationValidRequest)(nil),        // 3: com.ankama.dofus.server.game.protocol.alliance.information.AllianceEmblemModificationValidRequest
	(*AllianceNameAndTagModificationValidRequest)(nil),    // 4: com.ankama.dofus.server.game.protocol.alliance.information.AllianceNameAndTagModificationValidRequest
	(*AllianceModificationValidRequest)(nil),              // 5: com.ankama.dofus.server.game.protocol.alliance.information.AllianceModificationValidRequest
	(*AllianceMemberStartWarningOnConnectionRequest)(nil), // 6: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMemberStartWarningOnConnectionRequest
	(*AllianceMemberStopWarningOnConnectionRequest)(nil),  // 7: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMemberStopWarningOnConnectionRequest
	(*AllianceCreationStartedEvent)(nil),                  // 8: com.ankama.dofus.server.game.protocol.alliance.information.AllianceCreationStartedEvent
	(*AllianceModificationStartedEvent)(nil),              // 9: com.ankama.dofus.server.game.protocol.alliance.information.AllianceModificationStartedEvent
	(*AllianceCreationResultEvent)(nil),                   // 10: com.ankama.dofus.server.game.protocol.alliance.information.AllianceCreationResultEvent
	(*AllianceModificationResultEvent)(nil),               // 11: com.ankama.dofus.server.game.protocol.alliance.information.AllianceModificationResultEvent
	(*AllianceInsiderInformationRequest)(nil),             // 12: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationRequest
	(*AllianceFactsRequest)(nil),                          // 13: com.ankama.dofus.server.game.protocol.alliance.information.AllianceFactsRequest
	(*AllianceSummaryRequest)(nil),                        // 14: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest
	(*AllianceInsiderInformationEvent)(nil),               // 15: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationEvent
	(*AllianceFactsErrorEvent)(nil),                       // 16: com.ankama.dofus.server.game.protocol.alliance.information.AllianceFactsErrorEvent
	(*AllianceFactsEvent)(nil),                            // 17: com.ankama.dofus.server.game.protocol.alliance.information.AllianceFactsEvent
	(*AllianceSummaryEvent)(nil),                          // 18: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryEvent
	(*AllianceMotdSetRequest)(nil),                        // 19: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMotdSetRequest
	(*AllianceMotdEvent)(nil),                             // 20: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMotdEvent
	(*AllianceMotdSetErrorEvent)(nil),                     // 21: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMotdSetErrorEvent
	(*AllianceBulletinSetRequest)(nil),                    // 22: com.ankama.dofus.server.game.protocol.alliance.information.AllianceBulletinSetRequest
	(*AllianceBulletinEvent)(nil),                         // 23: com.ankama.dofus.server.game.protocol.alliance.information.AllianceBulletinEvent
	(*AllianceBulletinSetErrorEvent)(nil),                 // 24: com.ankama.dofus.server.game.protocol.alliance.information.AllianceBulletinSetErrorEvent
	(*common.SocialEmblem)(nil),                           // 25: com.ankama.dofus.server.game.protocol.common.SocialEmblem
	(common.SocialGroupOperationResult)(0),                // 26: com.ankama.dofus.server.game.protocol.common.SocialGroupOperationResult
	(common.SocialRecruitmentType)(0),                     // 27: com.ankama.dofus.server.game.protocol.common.SocialRecruitmentType
	(*common.AllianceInformation)(nil),                    // 28: com.ankama.dofus.server.game.protocol.common.AllianceInformation
	(*common.AllianceMemberInformation)(nil),              // 29: com.ankama.dofus.server.game.protocol.common.AllianceMemberInformation
	(*common.PrismLocalizedInformation)(nil),              // 30: com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation
	(*common.TaxCollectorInformation)(nil),                // 31: com.ankama.dofus.server.game.protocol.common.TaxCollectorInformation
	(*common.Character)(nil),                              // 32: com.ankama.dofus.server.game.protocol.common.Character
	(*common.SocialNoticeInformation)(nil),                // 33: com.ankama.dofus.server.game.protocol.common.SocialNoticeInformation
	(common.SocialNoticeError)(0),                         // 34: com.ankama.dofus.server.game.protocol.common.SocialNoticeError
}
var file_proto_game_alliance_information_proto_depIdxs = []int32{
	25, // 0: com.ankama.dofus.server.game.protocol.alliance.information.AllianceCreationValidRequest.alliance_emblem:type_name -> com.ankama.dofus.server.game.protocol.common.SocialEmblem
	25, // 1: com.ankama.dofus.server.game.protocol.alliance.information.AllianceEmblemModificationValidRequest.alliance_emblem:type_name -> com.ankama.dofus.server.game.protocol.common.SocialEmblem
	25, // 2: com.ankama.dofus.server.game.protocol.alliance.information.AllianceModificationValidRequest.alliance_emblem:type_name -> com.ankama.dofus.server.game.protocol.common.SocialEmblem
	26, // 3: com.ankama.dofus.server.game.protocol.alliance.information.AllianceCreationResultEvent.result:type_name -> com.ankama.dofus.server.game.protocol.common.SocialGroupOperationResult
	26, // 4: com.ankama.dofus.server.game.protocol.alliance.information.AllianceModificationResultEvent.result:type_name -> com.ankama.dofus.server.game.protocol.common.SocialGroupOperationResult
	0,  // 5: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.filter_type:type_name -> com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.DirectoryTextFilter
	1,  // 6: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.sort_type:type_name -> com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.AllianceSummarySort
	27, // 7: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryRequest.recruitment_type_filter:type_name -> com.ankama.dofus.server.game.protocol.common.SocialRecruitmentType
	28, // 8: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationEvent.information:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceInformation
	29, // 9: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationEvent.members:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceMemberInformation
	30, // 10: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationEvent.prisms:type_name -> com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation
	31, // 11: com.ankama.dofus.server.game.protocol.alliance.information.AllianceInsiderInformationEvent.tax_collectors:type_name -> com.ankama.dofus.server.game.protocol.common.TaxCollectorInformation
	28, // 12: com.ankama.dofus.server.game.protocol.alliance.information.AllianceFactsEvent.alliance_information:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceInformation
	32, // 13: com.ankama.dofus.server.game.protocol.alliance.information.AllianceFactsEvent.members:type_name -> com.ankama.dofus.server.game.protocol.common.Character
	28, // 14: com.ankama.dofus.server.game.protocol.alliance.information.AllianceSummaryEvent.alliances:type_name -> com.ankama.dofus.server.game.protocol.common.AllianceInformation
	33, // 15: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMotdEvent.motd_info:type_name -> com.ankama.dofus.server.game.protocol.common.SocialNoticeInformation
	34, // 16: com.ankama.dofus.server.game.protocol.alliance.information.AllianceMotdSetErrorEvent.reason:type_name -> com.ankama.dofus.server.game.protocol.common.SocialNoticeError
	33, // 17: com.ankama.dofus.server.game.protocol.alliance.information.AllianceBulletinEvent.bulletin_info:type_name -> com.ankama.dofus.server.game.protocol.common.SocialNoticeInformation
	34, // 18: com.ankama.dofus.server.game.protocol.alliance.information.AllianceBulletinSetErrorEvent.reason:type_name -> com.ankama.dofus.server.game.protocol.common.SocialNoticeError
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_game_alliance_information_proto_init() }
func file_proto_game_alliance_information_proto_init() {
	if File_proto_game_alliance_information_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_alliance_information_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceCreationValidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceEmblemModificationValidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceNameAndTagModificationValidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceModificationValidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceMemberStartWarningOnConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceMemberStopWarningOnConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceCreationStartedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceModificationStartedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceCreationResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceModificationResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceInsiderInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceFactsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceInsiderInformationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceFactsErrorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceFactsEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceSummaryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceMotdSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceMotdEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceMotdSetErrorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceBulletinSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceBulletinEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_alliance_information_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*AllianceBulletinSetErrorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_alliance_information_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_alliance_information_proto_goTypes,
		DependencyIndexes: file_proto_game_alliance_information_proto_depIdxs,
		EnumInfos:         file_proto_game_alliance_information_proto_enumTypes,
		MessageInfos:      file_proto_game_alliance_information_proto_msgTypes,
	}.Build()
	File_proto_game_alliance_information_proto = out.File
	file_proto_game_alliance_information_proto_rawDesc = nil
	file_proto_game_alliance_information_proto_goTypes = nil
	file_proto_game_alliance_information_proto_depIdxs = nil
}
