// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/shop.proto

package shop

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessoryPreviewErrorEvent_AccessoryPreviewError int32

const (
	AccessoryPreviewErrorEvent_ERROR     AccessoryPreviewErrorEvent_AccessoryPreviewError = 0
	AccessoryPreviewErrorEvent_COOL_DOWN AccessoryPreviewErrorEvent_AccessoryPreviewError = 1
	AccessoryPreviewErrorEvent_BAD_ITEM  AccessoryPreviewErrorEvent_AccessoryPreviewError = 2
)

// Enum value maps for AccessoryPreviewErrorEvent_AccessoryPreviewError.
var (
	AccessoryPreviewErrorEvent_AccessoryPreviewError_name = map[int32]string{
		0: "ERROR",
		1: "COOL_DOWN",
		2: "BAD_ITEM",
	}
	AccessoryPreviewErrorEvent_AccessoryPreviewError_value = map[string]int32{
		"ERROR":     0,
		"COOL_DOWN": 1,
		"BAD_ITEM":  2,
	}
)

func (x AccessoryPreviewErrorEvent_AccessoryPreviewError) Enum() *AccessoryPreviewErrorEvent_AccessoryPreviewError {
	p := new(AccessoryPreviewErrorEvent_AccessoryPreviewError)
	*p = x
	return p
}

func (x AccessoryPreviewErrorEvent_AccessoryPreviewError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessoryPreviewErrorEvent_AccessoryPreviewError) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_shop_proto_enumTypes[0].Descriptor()
}

func (AccessoryPreviewErrorEvent_AccessoryPreviewError) Type() protoreflect.EnumType {
	return &file_proto_game_shop_proto_enumTypes[0]
}

func (x AccessoryPreviewErrorEvent_AccessoryPreviewError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessoryPreviewErrorEvent_AccessoryPreviewError.Descriptor instead.
func (AccessoryPreviewErrorEvent_AccessoryPreviewError) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_shop_proto_rawDescGZIP(), []int{1, 0}
}

type AccessoryPreviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectGid          []int32 `protobuf:"varint,1,rep,packed,name=object_gid,json=objectGid,proto3" json:"object_gid,omitempty"`
	ShowCurrentObjects bool    `protobuf:"varint,2,opt,name=show_current_objects,json=showCurrentObjects,proto3" json:"show_current_objects,omitempty"`
}

func (x *AccessoryPreviewRequest) Reset() {
	*x = AccessoryPreviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessoryPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessoryPreviewRequest) ProtoMessage() {}

func (x *AccessoryPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessoryPreviewRequest.ProtoReflect.Descriptor instead.
func (*AccessoryPreviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_shop_proto_rawDescGZIP(), []int{0}
}

func (x *AccessoryPreviewRequest) GetObjectGid() []int32 {
	if x != nil {
		return x.ObjectGid
	}
	return nil
}

func (x *AccessoryPreviewRequest) GetShowCurrentObjects() bool {
	if x != nil {
		return x.ShowCurrentObjects
	}
	return false
}

type AccessoryPreviewErrorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error AccessoryPreviewErrorEvent_AccessoryPreviewError `protobuf:"varint,1,opt,name=error,proto3,enum=com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent_AccessoryPreviewError" json:"error,omitempty"`
}

func (x *AccessoryPreviewErrorEvent) Reset() {
	*x = AccessoryPreviewErrorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessoryPreviewErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessoryPreviewErrorEvent) ProtoMessage() {}

func (x *AccessoryPreviewErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessoryPreviewErrorEvent.ProtoReflect.Descriptor instead.
func (*AccessoryPreviewErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_shop_proto_rawDescGZIP(), []int{1}
}

func (x *AccessoryPreviewErrorEvent) GetError() AccessoryPreviewErrorEvent_AccessoryPreviewError {
	if x != nil {
		return x.Error
	}
	return AccessoryPreviewErrorEvent_ERROR
}

type AccessoryPreviewEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Look *common.EntityLook `protobuf:"bytes,1,opt,name=look,proto3" json:"look,omitempty"`
}

func (x *AccessoryPreviewEvent) Reset() {
	*x = AccessoryPreviewEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessoryPreviewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessoryPreviewEvent) ProtoMessage() {}

func (x *AccessoryPreviewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessoryPreviewEvent.ProtoReflect.Descriptor instead.
func (*AccessoryPreviewEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_shop_proto_rawDescGZIP(), []int{2}
}

func (x *AccessoryPreviewEvent) GetLook() *common.EntityLook {
	if x != nil {
		return x.Look
	}
	return nil
}

var File_proto_game_shop_proto protoreflect.FileDescriptor

var file_proto_game_shop_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b,
	0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6a, 0x0a, 0x17, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x79, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x73,
	0x68, 0x6f, 0x77, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x73, 0x68, 0x6f, 0x77, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0xd1, 0x01,
	0x0a, 0x1a, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x72, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x5c, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x79, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x3f, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4f, 0x4c, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x41, 0x44, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10,
	0x02, 0x22, 0x65, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x79, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4c, 0x0a, 0x04, 0x6c, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61,
	0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x6f,
	0x6f, 0x6b, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x6b, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x6f, 0x2d, 0x78,
	0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x68,
	0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_shop_proto_rawDescOnce sync.Once
	file_proto_game_shop_proto_rawDescData = file_proto_game_shop_proto_rawDesc
)

func file_proto_game_shop_proto_rawDescGZIP() []byte {
	file_proto_game_shop_proto_rawDescOnce.Do(func() {
		file_proto_game_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_shop_proto_rawDescData)
	})
	return file_proto_game_shop_proto_rawDescData
}

var file_proto_game_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_game_shop_proto_goTypes = []any{
	(AccessoryPreviewErrorEvent_AccessoryPreviewError)(0), // 0: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent.AccessoryPreviewError
	(*AccessoryPreviewRequest)(nil),                       // 1: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewRequest
	(*AccessoryPreviewErrorEvent)(nil),                    // 2: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent
	(*AccessoryPreviewEvent)(nil),                         // 3: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewEvent
	(*common.EntityLook)(nil),                             // 4: com.ankama.dofus.server.game.protocol.common.EntityLook
}
var file_proto_game_shop_proto_depIdxs = []int32{
	0, // 0: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent.error:type_name -> com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent.AccessoryPreviewError
	4, // 1: com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewEvent.look:type_name -> com.ankama.dofus.server.game.protocol.common.EntityLook
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_game_shop_proto_init() }
func file_proto_game_shop_proto_init() {
	if File_proto_game_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_shop_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccessoryPreviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_shop_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccessoryPreviewErrorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_shop_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AccessoryPreviewEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_shop_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_shop_proto_goTypes,
		DependencyIndexes: file_proto_game_shop_proto_depIdxs,
		EnumInfos:         file_proto_game_shop_proto_enumTypes,
		MessageInfos:      file_proto_game_shop_proto_msgTypes,
	}.Build()
	File_proto_game_shop_proto = out.File
	file_proto_game_shop_proto_rawDesc = nil
	file_proto_game_shop_proto_goTypes = nil
	file_proto_game_shop_proto_depIdxs = nil
}
