// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/symbiont.proto

package symbiont

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MimicryResponse_Result int32

const (
	MimicryResponse_ERROR               MimicryResponse_Result = 0
	MimicryResponse_PLAYER_BUSY         MimicryResponse_Result = 1
	MimicryResponse_HOST_NOT_MIMICKABLE MimicryResponse_Result = 2
	MimicryResponse_HOST_WRAPPED        MimicryResponse_Result = 3
	MimicryResponse_DUPLICATE           MimicryResponse_Result = 4
	MimicryResponse_SUCCESS             MimicryResponse_Result = 5
)

// Enum value maps for MimicryResponse_Result.
var (
	MimicryResponse_Result_name = map[int32]string{
		0: "ERROR",
		1: "PLAYER_BUSY",
		2: "HOST_NOT_MIMICKABLE",
		3: "HOST_WRAPPED",
		4: "DUPLICATE",
		5: "SUCCESS",
	}
	MimicryResponse_Result_value = map[string]int32{
		"ERROR":               0,
		"PLAYER_BUSY":         1,
		"HOST_NOT_MIMICKABLE": 2,
		"HOST_WRAPPED":        3,
		"DUPLICATE":           4,
		"SUCCESS":             5,
	}
)

func (x MimicryResponse_Result) Enum() *MimicryResponse_Result {
	p := new(MimicryResponse_Result)
	*p = x
	return p
}

func (x MimicryResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MimicryResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_symbiont_proto_enumTypes[0].Descriptor()
}

func (MimicryResponse_Result) Type() protoreflect.EnumType {
	return &file_proto_game_symbiont_proto_enumTypes[0]
}

func (x MimicryResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MimicryResponse_Result.Descriptor instead.
func (MimicryResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{2, 0}
}

type WrapperObjectDissociateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostUid      int32 `protobuf:"varint,1,opt,name=host_uid,json=hostUid,proto3" json:"host_uid,omitempty"`
	HostPosition int32 `protobuf:"varint,2,opt,name=host_position,json=hostPosition,proto3" json:"host_position,omitempty"`
}

func (x *WrapperObjectDissociateRequest) Reset() {
	*x = WrapperObjectDissociateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_symbiont_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WrapperObjectDissociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperObjectDissociateRequest) ProtoMessage() {}

func (x *WrapperObjectDissociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_symbiont_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperObjectDissociateRequest.ProtoReflect.Descriptor instead.
func (*WrapperObjectDissociateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{0}
}

func (x *WrapperObjectDissociateRequest) GetHostUid() int32 {
	if x != nil {
		return x.HostUid
	}
	return 0
}

func (x *WrapperObjectDissociateRequest) GetHostPosition() int32 {
	if x != nil {
		return x.HostPosition
	}
	return 0
}

type MimicryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SymbiontUid int32 `protobuf:"varint,1,opt,name=symbiont_uid,json=symbiontUid,proto3" json:"symbiont_uid,omitempty"`
	HostUid     int32 `protobuf:"varint,2,opt,name=host_uid,json=hostUid,proto3" json:"host_uid,omitempty"`
}

func (x *MimicryRequest) Reset() {
	*x = MimicryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_symbiont_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MimicryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MimicryRequest) ProtoMessage() {}

func (x *MimicryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_symbiont_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MimicryRequest.ProtoReflect.Descriptor instead.
func (*MimicryRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{1}
}

func (x *MimicryRequest) GetSymbiontUid() int32 {
	if x != nil {
		return x.SymbiontUid
	}
	return 0
}

func (x *MimicryRequest) GetHostUid() int32 {
	if x != nil {
		return x.HostUid
	}
	return 0
}

type MimicryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MimicryResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=com.ankama.dofus.server.game.protocol.symbiont.MimicryResponse_Result" json:"result,omitempty"`
}

func (x *MimicryResponse) Reset() {
	*x = MimicryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_symbiont_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MimicryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MimicryResponse) ProtoMessage() {}

func (x *MimicryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_symbiont_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MimicryResponse.ProtoReflect.Descriptor instead.
func (*MimicryResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{2}
}

func (x *MimicryResponse) GetResult() MimicryResponse_Result {
	if x != nil {
		return x.Result
	}
	return MimicryResponse_ERROR
}

type MimicryFreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostUid int32 `protobuf:"varint,1,opt,name=host_uid,json=hostUid,proto3" json:"host_uid,omitempty"`
}

func (x *MimicryFreeRequest) Reset() {
	*x = MimicryFreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_symbiont_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MimicryFreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MimicryFreeRequest) ProtoMessage() {}

func (x *MimicryFreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_symbiont_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MimicryFreeRequest.ProtoReflect.Descriptor instead.
func (*MimicryFreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{3}
}

func (x *MimicryFreeRequest) GetHostUid() int32 {
	if x != nil {
		return x.HostUid
	}
	return 0
}

type MimicryFreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MimicryFreeResponse) Reset() {
	*x = MimicryFreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_symbiont_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MimicryFreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MimicryFreeResponse) ProtoMessage() {}

func (x *MimicryFreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_symbiont_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MimicryFreeResponse.ProtoReflect.Descriptor instead.
func (*MimicryFreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_symbiont_proto_rawDescGZIP(), []int{4}
}

func (x *MimicryFreeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_game_symbiont_proto protoreflect.FileDescriptor

var file_proto_game_symbiont_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x79, 0x6d,
	0x62, 0x69, 0x6f, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x1e, 0x57,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a,
	0x0e, 0x4d, 0x69, 0x6d, 0x69, 0x63, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x6e, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x6e, 0x74, 0x55,
	0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x69, 0x64, 0x22, 0xde, 0x01,
	0x0a, 0x0f, 0x4d, 0x69, 0x6d, 0x69, 0x63, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x46, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64,
	0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f,
	0x6e, 0x74, 0x2e, 0x4d, 0x69, 0x6d, 0x69, 0x63, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x6b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x42, 0x55, 0x53, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x48, 0x4f, 0x53, 0x54, 0x5f,
	0x4e, 0x4f, 0x54, 0x5f, 0x4d, 0x49, 0x4d, 0x49, 0x43, 0x4b, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x48, 0x4f, 0x53, 0x54, 0x5f, 0x57, 0x52, 0x41, 0x50, 0x50, 0x45, 0x44,
	0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x10,
	0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x05, 0x22, 0x2f,
	0x0a, 0x12, 0x4d, 0x69, 0x6d, 0x69, 0x63, 0x72, 0x79, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x13, 0x4d, 0x69, 0x6d, 0x69, 0x63, 0x72, 0x79, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x6f, 0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_symbiont_proto_rawDescOnce sync.Once
	file_proto_game_symbiont_proto_rawDescData = file_proto_game_symbiont_proto_rawDesc
)

func file_proto_game_symbiont_proto_rawDescGZIP() []byte {
	file_proto_game_symbiont_proto_rawDescOnce.Do(func() {
		file_proto_game_symbiont_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_symbiont_proto_rawDescData)
	})
	return file_proto_game_symbiont_proto_rawDescData
}

var file_proto_game_symbiont_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_symbiont_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_game_symbiont_proto_goTypes = []any{
	(MimicryResponse_Result)(0),            // 0: com.ankama.dofus.server.game.protocol.symbiont.MimicryResponse.Result
	(*WrapperObjectDissociateRequest)(nil), // 1: com.ankama.dofus.server.game.protocol.symbiont.WrapperObjectDissociateRequest
	(*MimicryRequest)(nil),                 // 2: com.ankama.dofus.server.game.protocol.symbiont.MimicryRequest
	(*MimicryResponse)(nil),                // 3: com.ankama.dofus.server.game.protocol.symbiont.MimicryResponse
	(*MimicryFreeRequest)(nil),             // 4: com.ankama.dofus.server.game.protocol.symbiont.MimicryFreeRequest
	(*MimicryFreeResponse)(nil),            // 5: com.ankama.dofus.server.game.protocol.symbiont.MimicryFreeResponse
}
var file_proto_game_symbiont_proto_depIdxs = []int32{
	0, // 0: com.ankama.dofus.server.game.protocol.symbiont.MimicryResponse.result:type_name -> com.ankama.dofus.server.game.protocol.symbiont.MimicryResponse.Result
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_game_symbiont_proto_init() }
func file_proto_game_symbiont_proto_init() {
	if File_proto_game_symbiont_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_symbiont_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WrapperObjectDissociateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_symbiont_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MimicryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_symbiont_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MimicryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_symbiont_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MimicryFreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_symbiont_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MimicryFreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_symbiont_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_symbiont_proto_goTypes,
		DependencyIndexes: file_proto_game_symbiont_proto_depIdxs,
		EnumInfos:         file_proto_game_symbiont_proto_enumTypes,
		MessageInfos:      file_proto_game_symbiont_proto_msgTypes,
	}.Build()
	File_proto_game_symbiont_proto = out.File
	file_proto_game_symbiont_proto_rawDesc = nil
	file_proto_game_symbiont_proto_goTypes = nil
	file_proto_game_symbiont_proto_depIdxs = nil
}
