// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/haven_bag.proto

package haven_bag

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HavenBagRoomUpdateEvent_HavenBagRoomAction int32

const (
	HavenBagRoomUpdateEvent_HAVEN_BAG_ROOM_DISPATCH HavenBagRoomUpdateEvent_HavenBagRoomAction = 0
	HavenBagRoomUpdateEvent_HAVEN_BAG_ROOM_UPDATE   HavenBagRoomUpdateEvent_HavenBagRoomAction = 1
)

// Enum value maps for HavenBagRoomUpdateEvent_HavenBagRoomAction.
var (
	HavenBagRoomUpdateEvent_HavenBagRoomAction_name = map[int32]string{
		0: "HAVEN_BAG_ROOM_DISPATCH",
		1: "HAVEN_BAG_ROOM_UPDATE",
	}
	HavenBagRoomUpdateEvent_HavenBagRoomAction_value = map[string]int32{
		"HAVEN_BAG_ROOM_DISPATCH": 0,
		"HAVEN_BAG_ROOM_UPDATE":   1,
	}
)

func (x HavenBagRoomUpdateEvent_HavenBagRoomAction) Enum() *HavenBagRoomUpdateEvent_HavenBagRoomAction {
	p := new(HavenBagRoomUpdateEvent_HavenBagRoomAction)
	*p = x
	return p
}

func (x HavenBagRoomUpdateEvent_HavenBagRoomAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HavenBagRoomUpdateEvent_HavenBagRoomAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_haven_bag_proto_enumTypes[0].Descriptor()
}

func (HavenBagRoomUpdateEvent_HavenBagRoomAction) Type() protoreflect.EnumType {
	return &file_proto_game_haven_bag_proto_enumTypes[0]
}

func (x HavenBagRoomUpdateEvent_HavenBagRoomAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HavenBagRoomUpdateEvent_HavenBagRoomAction.Descriptor instead.
func (HavenBagRoomUpdateEvent_HavenBagRoomAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{13, 0}
}

type HavenBagDailyLotteryEvent_DailyLotteryResult int32

const (
	HavenBagDailyLotteryEvent_HAVEN_BAG_DAILY_LOTTERY_OK           HavenBagDailyLotteryEvent_DailyLotteryResult = 0
	HavenBagDailyLotteryEvent_HAVEN_BAG_DAILY_LOTTERY_ALREADY_USED HavenBagDailyLotteryEvent_DailyLotteryResult = 1
	HavenBagDailyLotteryEvent_HAVEN_BAG_DAILY_LOTTERY_ERROR        HavenBagDailyLotteryEvent_DailyLotteryResult = 2
)

// Enum value maps for HavenBagDailyLotteryEvent_DailyLotteryResult.
var (
	HavenBagDailyLotteryEvent_DailyLotteryResult_name = map[int32]string{
		0: "HAVEN_BAG_DAILY_LOTTERY_OK",
		1: "HAVEN_BAG_DAILY_LOTTERY_ALREADY_USED",
		2: "HAVEN_BAG_DAILY_LOTTERY_ERROR",
	}
	HavenBagDailyLotteryEvent_DailyLotteryResult_value = map[string]int32{
		"HAVEN_BAG_DAILY_LOTTERY_OK":           0,
		"HAVEN_BAG_DAILY_LOTTERY_ALREADY_USED": 1,
		"HAVEN_BAG_DAILY_LOTTERY_ERROR":        2,
	}
)

func (x HavenBagDailyLotteryEvent_DailyLotteryResult) Enum() *HavenBagDailyLotteryEvent_DailyLotteryResult {
	p := new(HavenBagDailyLotteryEvent_DailyLotteryResult)
	*p = x
	return p
}

func (x HavenBagDailyLotteryEvent_DailyLotteryResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HavenBagDailyLotteryEvent_DailyLotteryResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_haven_bag_proto_enumTypes[1].Descriptor()
}

func (HavenBagDailyLotteryEvent_DailyLotteryResult) Type() protoreflect.EnumType {
	return &file_proto_game_haven_bag_proto_enumTypes[1]
}

func (x HavenBagDailyLotteryEvent_DailyLotteryResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HavenBagDailyLotteryEvent_DailyLotteryResult.Descriptor instead.
func (HavenBagDailyLotteryEvent_DailyLotteryResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{17, 0}
}

type HavenBagEnterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner int64 `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *HavenBagEnterRequest) Reset() {
	*x = HavenBagEnterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagEnterRequest) ProtoMessage() {}

func (x *HavenBagEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagEnterRequest.ProtoReflect.Descriptor instead.
func (*HavenBagEnterRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{0}
}

func (x *HavenBagEnterRequest) GetOwner() int64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

type HavenBagChangeRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *HavenBagChangeRoomRequest) Reset() {
	*x = HavenBagChangeRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagChangeRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagChangeRoomRequest) ProtoMessage() {}

func (x *HavenBagChangeRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagChangeRoomRequest.ProtoReflect.Descriptor instead.
func (*HavenBagChangeRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{1}
}

func (x *HavenBagChangeRoomRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type HavenBagExitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagExitRequest) Reset() {
	*x = HavenBagExitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagExitRequest) ProtoMessage() {}

func (x *HavenBagExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagExitRequest.ProtoReflect.Descriptor instead.
func (*HavenBagExitRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{2}
}

type HavenBagEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagEditRequest) Reset() {
	*x = HavenBagEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagEditRequest) ProtoMessage() {}

func (x *HavenBagEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagEditRequest.ProtoReflect.Descriptor instead.
func (*HavenBagEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{3}
}

type HavenBagEditCancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagEditCancelRequest) Reset() {
	*x = HavenBagEditCancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagEditCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagEditCancelRequest) ProtoMessage() {}

func (x *HavenBagEditCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagEditCancelRequest.ProtoReflect.Descriptor instead.
func (*HavenBagEditCancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{4}
}

type HavenBagThemeChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme int32 `protobuf:"varint,1,opt,name=theme,proto3" json:"theme,omitempty"`
}

func (x *HavenBagThemeChangeRequest) Reset() {
	*x = HavenBagThemeChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagThemeChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagThemeChangeRequest) ProtoMessage() {}

func (x *HavenBagThemeChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagThemeChangeRequest.ProtoReflect.Descriptor instead.
func (*HavenBagThemeChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{5}
}

func (x *HavenBagThemeChangeRequest) GetTheme() int32 {
	if x != nil {
		return x.Theme
	}
	return 0
}

type HavenBagFurnitureOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagFurnitureOpenRequest) Reset() {
	*x = HavenBagFurnitureOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagFurnitureOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagFurnitureOpenRequest) ProtoMessage() {}

func (x *HavenBagFurnitureOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagFurnitureOpenRequest.ProtoReflect.Descriptor instead.
func (*HavenBagFurnitureOpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{6}
}

type HavenBagFurnitureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Furniture []*Element `protobuf:"bytes,1,rep,name=furniture,proto3" json:"furniture,omitempty"`
}

func (x *HavenBagFurnitureRequest) Reset() {
	*x = HavenBagFurnitureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagFurnitureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagFurnitureRequest) ProtoMessage() {}

func (x *HavenBagFurnitureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagFurnitureRequest.ProtoReflect.Descriptor instead.
func (*HavenBagFurnitureRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{7}
}

func (x *HavenBagFurnitureRequest) GetFurniture() []*Element {
	if x != nil {
		return x.Furniture
	}
	return nil
}

type HavenBagFurnitureCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagFurnitureCloseRequest) Reset() {
	*x = HavenBagFurnitureCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagFurnitureCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagFurnitureCloseRequest) ProtoMessage() {}

func (x *HavenBagFurnitureCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagFurnitureCloseRequest.ProtoReflect.Descriptor instead.
func (*HavenBagFurnitureCloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{8}
}

type HavenBagKickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuestId int64 `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
}

func (x *HavenBagKickRequest) Reset() {
	*x = HavenBagKickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagKickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagKickRequest) ProtoMessage() {}

func (x *HavenBagKickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagKickRequest.ProtoReflect.Descriptor instead.
func (*HavenBagKickRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{9}
}

func (x *HavenBagKickRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

type HavenBagPermissionsUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions int32 `protobuf:"varint,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *HavenBagPermissionsUpdateRequest) Reset() {
	*x = HavenBagPermissionsUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagPermissionsUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagPermissionsUpdateRequest) ProtoMessage() {}

func (x *HavenBagPermissionsUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagPermissionsUpdateRequest.ProtoReflect.Descriptor instead.
func (*HavenBagPermissionsUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{10}
}

func (x *HavenBagPermissionsUpdateRequest) GetPermissions() int32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type HavenBagInvitationAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *HavenBagInvitationAnswerRequest) Reset() {
	*x = HavenBagInvitationAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagInvitationAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagInvitationAnswerRequest) ProtoMessage() {}

func (x *HavenBagInvitationAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagInvitationAnswerRequest.ProtoReflect.Descriptor instead.
func (*HavenBagInvitationAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{11}
}

func (x *HavenBagInvitationAnswerRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HavenBagInvitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuestId int64 `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
}

func (x *HavenBagInvitationRequest) Reset() {
	*x = HavenBagInvitationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagInvitationRequest) ProtoMessage() {}

func (x *HavenBagInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagInvitationRequest.ProtoReflect.Descriptor instead.
func (*HavenBagInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{12}
}

func (x *HavenBagInvitationRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

type HavenBagRoomUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  HavenBagRoomUpdateEvent_HavenBagRoomAction     `protobuf:"varint,1,opt,name=action,proto3,enum=com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent_HavenBagRoomAction" json:"action,omitempty"`
	Preview []*HavenBagRoomUpdateEvent_HavenBagRoomPreview `protobuf:"bytes,2,rep,name=preview,proto3" json:"preview,omitempty"`
}

func (x *HavenBagRoomUpdateEvent) Reset() {
	*x = HavenBagRoomUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagRoomUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagRoomUpdateEvent) ProtoMessage() {}

func (x *HavenBagRoomUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagRoomUpdateEvent.ProtoReflect.Descriptor instead.
func (*HavenBagRoomUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{13}
}

func (x *HavenBagRoomUpdateEvent) GetAction() HavenBagRoomUpdateEvent_HavenBagRoomAction {
	if x != nil {
		return x.Action
	}
	return HavenBagRoomUpdateEvent_HAVEN_BAG_ROOM_DISPATCH
}

func (x *HavenBagRoomUpdateEvent) GetPreview() []*HavenBagRoomUpdateEvent_HavenBagRoomPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

type HavenBagPackListEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacksId []int32 `protobuf:"varint,1,rep,packed,name=packs_id,json=packsId,proto3" json:"packs_id,omitempty"`
}

func (x *HavenBagPackListEvent) Reset() {
	*x = HavenBagPackListEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagPackListEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagPackListEvent) ProtoMessage() {}

func (x *HavenBagPackListEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagPackListEvent.ProtoReflect.Descriptor instead.
func (*HavenBagPackListEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{14}
}

func (x *HavenBagPackListEvent) GetPacksId() []int32 {
	if x != nil {
		return x.PacksId
	}
	return nil
}

type HavenBagEditStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagEditStartEvent) Reset() {
	*x = HavenBagEditStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagEditStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagEditStartEvent) ProtoMessage() {}

func (x *HavenBagEditStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagEditStartEvent.ProtoReflect.Descriptor instead.
func (*HavenBagEditStartEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{15}
}

type HavenBagEditFinishedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HavenBagEditFinishedEvent) Reset() {
	*x = HavenBagEditFinishedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagEditFinishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagEditFinishedEvent) ProtoMessage() {}

func (x *HavenBagEditFinishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagEditFinishedEvent.ProtoReflect.Descriptor instead.
func (*HavenBagEditFinishedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{16}
}

type HavenBagDailyLotteryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       HavenBagDailyLotteryEvent_DailyLotteryResult `protobuf:"varint,1,opt,name=result,proto3,enum=com.ankama.dofus.server.game.protocol.haven.bag.HavenBagDailyLotteryEvent_DailyLotteryResult" json:"result,omitempty"`
	GameActionId *int64                                       `protobuf:"varint,2,opt,name=game_action_id,json=gameActionId,proto3,oneof" json:"game_action_id,omitempty"`
}

func (x *HavenBagDailyLotteryEvent) Reset() {
	*x = HavenBagDailyLotteryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagDailyLotteryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagDailyLotteryEvent) ProtoMessage() {}

func (x *HavenBagDailyLotteryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagDailyLotteryEvent.ProtoReflect.Descriptor instead.
func (*HavenBagDailyLotteryEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{17}
}

func (x *HavenBagDailyLotteryEvent) GetResult() HavenBagDailyLotteryEvent_DailyLotteryResult {
	if x != nil {
		return x.Result
	}
	return HavenBagDailyLotteryEvent_HAVEN_BAG_DAILY_LOTTERY_OK
}

func (x *HavenBagDailyLotteryEvent) GetGameActionId() int64 {
	if x != nil && x.GameActionId != nil {
		return *x.GameActionId
	}
	return 0
}

type HavenBagFurnitureEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Furniture []*Element `protobuf:"bytes,1,rep,name=furniture,proto3" json:"furniture,omitempty"`
}

func (x *HavenBagFurnitureEvent) Reset() {
	*x = HavenBagFurnitureEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagFurnitureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagFurnitureEvent) ProtoMessage() {}

func (x *HavenBagFurnitureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagFurnitureEvent.ProtoReflect.Descriptor instead.
func (*HavenBagFurnitureEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{18}
}

func (x *HavenBagFurnitureEvent) GetFurniture() []*Element {
	if x != nil {
		return x.Furniture
	}
	return nil
}

type HavenBagPermissionsUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions int32 `protobuf:"varint,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *HavenBagPermissionsUpdateEvent) Reset() {
	*x = HavenBagPermissionsUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagPermissionsUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagPermissionsUpdateEvent) ProtoMessage() {}

func (x *HavenBagPermissionsUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagPermissionsUpdateEvent.ProtoReflect.Descriptor instead.
func (*HavenBagPermissionsUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{19}
}

func (x *HavenBagPermissionsUpdateEvent) GetPermissions() int32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type HavenBagInvitationClosedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostInformation *common.Character `protobuf:"bytes,1,opt,name=host_information,json=hostInformation,proto3" json:"host_information,omitempty"`
}

func (x *HavenBagInvitationClosedEvent) Reset() {
	*x = HavenBagInvitationClosedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagInvitationClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagInvitationClosedEvent) ProtoMessage() {}

func (x *HavenBagInvitationClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagInvitationClosedEvent.ProtoReflect.Descriptor instead.
func (*HavenBagInvitationClosedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{20}
}

func (x *HavenBagInvitationClosedEvent) GetHostInformation() *common.Character {
	if x != nil {
		return x.HostInformation
	}
	return nil
}

type HavenBagInvitationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuestInformation *common.Character `protobuf:"bytes,1,opt,name=guest_information,json=guestInformation,proto3" json:"guest_information,omitempty"`
	Accepted         bool              `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *HavenBagInvitationEvent) Reset() {
	*x = HavenBagInvitationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagInvitationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagInvitationEvent) ProtoMessage() {}

func (x *HavenBagInvitationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagInvitationEvent.ProtoReflect.Descriptor instead.
func (*HavenBagInvitationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{21}
}

func (x *HavenBagInvitationEvent) GetGuestInformation() *common.Character {
	if x != nil {
		return x.GuestInformation
	}
	return nil
}

func (x *HavenBagInvitationEvent) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HavenBagInvitationOfferedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostInformation  *common.Character `protobuf:"bytes,1,opt,name=host_information,json=hostInformation,proto3" json:"host_information,omitempty"`
	TimeBeforeCancel int64             `protobuf:"varint,2,opt,name=time_before_cancel,json=timeBeforeCancel,proto3" json:"time_before_cancel,omitempty"`
}

func (x *HavenBagInvitationOfferedEvent) Reset() {
	*x = HavenBagInvitationOfferedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagInvitationOfferedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagInvitationOfferedEvent) ProtoMessage() {}

func (x *HavenBagInvitationOfferedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagInvitationOfferedEvent.ProtoReflect.Descriptor instead.
func (*HavenBagInvitationOfferedEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{22}
}

func (x *HavenBagInvitationOfferedEvent) GetHostInformation() *common.Character {
	if x != nil {
		return x.HostInformation
	}
	return nil
}

func (x *HavenBagInvitationOfferedEvent) GetTimeBeforeCancel() int64 {
	if x != nil {
		return x.TimeBeforeCancel
	}
	return 0
}

type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId      int32 `protobuf:"varint,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	ElementId   int32 `protobuf:"varint,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Orientation int32 `protobuf:"varint,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{23}
}

func (x *Element) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *Element) GetElementId() int32 {
	if x != nil {
		return x.ElementId
	}
	return 0
}

func (x *Element) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

type HavenBagRoomUpdateEvent_HavenBagRoomPreview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThemeId int32 `protobuf:"varint,2,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
}

func (x *HavenBagRoomUpdateEvent_HavenBagRoomPreview) Reset() {
	*x = HavenBagRoomUpdateEvent_HavenBagRoomPreview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_haven_bag_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HavenBagRoomUpdateEvent_HavenBagRoomPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HavenBagRoomUpdateEvent_HavenBagRoomPreview) ProtoMessage() {}

func (x *HavenBagRoomUpdateEvent_HavenBagRoomPreview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_haven_bag_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HavenBagRoomUpdateEvent_HavenBagRoomPreview.ProtoReflect.Descriptor instead.
func (*HavenBagRoomUpdateEvent_HavenBagRoomPreview) Descriptor() ([]byte, []int) {
	return file_proto_game_haven_bag_proto_rawDescGZIP(), []int{13, 0}
}

func (x *HavenBagRoomUpdateEvent_HavenBagRoomPreview) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *HavenBagRoomUpdateEvent_HavenBagRoomPreview) GetThemeId() int32 {
	if x != nil {
		return x.ThemeId
	}
	return 0
}

var File_proto_game_haven_bag_proto protoreflect.FileDescriptor

var file_proto_game_haven_bag_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x5f, 0x62, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x62, 0x61, 0x67, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x14, 0x48,
	0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x19, 0x48, 0x61, 0x76,
	0x65, 0x6e, 0x42, 0x61, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x15, 0x0a, 0x13, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x45, 0x78, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42,
	0x61, 0x67, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a,
	0x19, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x1a, 0x48, 0x61,
	0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x22, 0x1e,
	0x0a, 0x1c, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x46, 0x75, 0x72, 0x6e, 0x69, 0x74,
	0x75, 0x72, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x72,
	0x0a, 0x18, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x46, 0x75, 0x72, 0x6e, 0x69, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x09, 0x66, 0x75,
	0x72, 0x6e, 0x69, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x62, 0x61, 0x67, 0x2e,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x66, 0x75, 0x72, 0x6e, 0x69, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x46, 0x75,
	0x72, 0x6e, 0x69, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x13, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x4b,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x20, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61,
	0x67, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3d, 0x0a, 0x1f, 0x48,
	0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0x36, 0x0a, 0x19, 0x48, 0x61,
	0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x9f, 0x03, 0x0a, 0x17, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x73,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x5b,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75,
	0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x62, 0x61, 0x67,
	0x2e, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61,
	0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x76, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x5c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d,
	0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x2e, 0x62, 0x61, 0x67, 0x2e, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x48,
	0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x1a, 0x49, 0x0a, 0x13, 0x48,
	0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x12, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42,
	0x61, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x17,
	0x48, 0x41, 0x56, 0x45, 0x4e, 0x5f, 0x42, 0x41, 0x47, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x44,
	0x49, 0x53, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x48, 0x41, 0x56,
	0x45, 0x4e, 0x5f, 0x42, 0x41, 0x47, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x10, 0x01, 0x22, 0x32, 0x0a, 0x15, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67,
	0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x48, 0x61, 0x76, 0x65,
	0x6e, 0x42, 0x61, 0x67, 0x45, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x45, 0x64,
	0x69, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0xd4, 0x02, 0x0a, 0x19, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x44, 0x61, 0x69, 0x6c,
	0x79, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x75, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x5d, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x62, 0x61, 0x67, 0x2e,
	0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c,
	0x67, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x22,
	0x81, 0x01, 0x0a, 0x12, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x1a, 0x48, 0x41, 0x56, 0x45, 0x4e, 0x5f,
	0x42, 0x41, 0x47, 0x5f, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x5f, 0x4c, 0x4f, 0x54, 0x54, 0x45, 0x52,
	0x59, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x48, 0x41, 0x56, 0x45, 0x4e, 0x5f,
	0x42, 0x41, 0x47, 0x5f, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x5f, 0x4c, 0x4f, 0x54, 0x54, 0x45, 0x52,
	0x59, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x21, 0x0a, 0x1d, 0x48, 0x41, 0x56, 0x45, 0x4e, 0x5f, 0x42, 0x41, 0x47, 0x5f, 0x44, 0x41,
	0x49, 0x4c, 0x59, 0x5f, 0x4c, 0x4f, 0x54, 0x54, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x16, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42,
	0x61, 0x67, 0x46, 0x75, 0x72, 0x6e, 0x69, 0x74, 0x75, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x56, 0x0a, 0x09, 0x66, 0x75, 0x72, 0x6e, 0x69, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x76, 0x65,
	0x6e, 0x2e, 0x62, 0x61, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x66,
	0x75, 0x72, 0x6e, 0x69, 0x74, 0x75, 0x72, 0x65, 0x22, 0x42, 0x0a, 0x1e, 0x48, 0x61, 0x76, 0x65,
	0x6e, 0x42, 0x61, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x83, 0x01, 0x0a,
	0x1d, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x62,
	0x0a, 0x10, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61,
	0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x52, 0x0f, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x9b, 0x01, 0x0a, 0x17, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x64,
	0x0a, 0x11, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x52, 0x10, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x22, 0xb2, 0x01, 0x0a, 0x1e, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x10, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x0f, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x22, 0x63, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x6f,
	0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x5f, 0x62, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_game_haven_bag_proto_rawDescOnce sync.Once
	file_proto_game_haven_bag_proto_rawDescData = file_proto_game_haven_bag_proto_rawDesc
)

func file_proto_game_haven_bag_proto_rawDescGZIP() []byte {
	file_proto_game_haven_bag_proto_rawDescOnce.Do(func() {
		file_proto_game_haven_bag_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_haven_bag_proto_rawDescData)
	})
	return file_proto_game_haven_bag_proto_rawDescData
}

var file_proto_game_haven_bag_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_game_haven_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_game_haven_bag_proto_goTypes = []any{
	(HavenBagRoomUpdateEvent_HavenBagRoomAction)(0),     // 0: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.HavenBagRoomAction
	(HavenBagDailyLotteryEvent_DailyLotteryResult)(0),   // 1: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagDailyLotteryEvent.DailyLotteryResult
	(*HavenBagEnterRequest)(nil),                        // 2: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagEnterRequest
	(*HavenBagChangeRoomRequest)(nil),                   // 3: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagChangeRoomRequest
	(*HavenBagExitRequest)(nil),                         // 4: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagExitRequest
	(*HavenBagEditRequest)(nil),                         // 5: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagEditRequest
	(*HavenBagEditCancelRequest)(nil),                   // 6: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagEditCancelRequest
	(*HavenBagThemeChangeRequest)(nil),                  // 7: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagThemeChangeRequest
	(*HavenBagFurnitureOpenRequest)(nil),                // 8: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureOpenRequest
	(*HavenBagFurnitureRequest)(nil),                    // 9: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureRequest
	(*HavenBagFurnitureCloseRequest)(nil),               // 10: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureCloseRequest
	(*HavenBagKickRequest)(nil),                         // 11: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagKickRequest
	(*HavenBagPermissionsUpdateRequest)(nil),            // 12: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagPermissionsUpdateRequest
	(*HavenBagInvitationAnswerRequest)(nil),             // 13: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationAnswerRequest
	(*HavenBagInvitationRequest)(nil),                   // 14: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationRequest
	(*HavenBagRoomUpdateEvent)(nil),                     // 15: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent
	(*HavenBagPackListEvent)(nil),                       // 16: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagPackListEvent
	(*HavenBagEditStartEvent)(nil),                      // 17: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagEditStartEvent
	(*HavenBagEditFinishedEvent)(nil),                   // 18: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagEditFinishedEvent
	(*HavenBagDailyLotteryEvent)(nil),                   // 19: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagDailyLotteryEvent
	(*HavenBagFurnitureEvent)(nil),                      // 20: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureEvent
	(*HavenBagPermissionsUpdateEvent)(nil),              // 21: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagPermissionsUpdateEvent
	(*HavenBagInvitationClosedEvent)(nil),               // 22: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationClosedEvent
	(*HavenBagInvitationEvent)(nil),                     // 23: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationEvent
	(*HavenBagInvitationOfferedEvent)(nil),              // 24: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationOfferedEvent
	(*Element)(nil),                                     // 25: com.ankama.dofus.server.game.protocol.haven.bag.Element
	(*HavenBagRoomUpdateEvent_HavenBagRoomPreview)(nil), // 26: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.HavenBagRoomPreview
	(*common.Character)(nil),                            // 27: com.ankama.dofus.server.game.protocol.common.Character
}
var file_proto_game_haven_bag_proto_depIdxs = []int32{
	25, // 0: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureRequest.furniture:type_name -> com.ankama.dofus.server.game.protocol.haven.bag.Element
	0,  // 1: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.action:type_name -> com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.HavenBagRoomAction
	26, // 2: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.preview:type_name -> com.ankama.dofus.server.game.protocol.haven.bag.HavenBagRoomUpdateEvent.HavenBagRoomPreview
	1,  // 3: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagDailyLotteryEvent.result:type_name -> com.ankama.dofus.server.game.protocol.haven.bag.HavenBagDailyLotteryEvent.DailyLotteryResult
	25, // 4: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagFurnitureEvent.furniture:type_name -> com.ankama.dofus.server.game.protocol.haven.bag.Element
	27, // 5: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationClosedEvent.host_information:type_name -> com.ankama.dofus.server.game.protocol.common.Character
	27, // 6: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationEvent.guest_information:type_name -> com.ankama.dofus.server.game.protocol.common.Character
	27, // 7: com.ankama.dofus.server.game.protocol.haven.bag.HavenBagInvitationOfferedEvent.host_information:type_name -> com.ankama.dofus.server.game.protocol.common.Character
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_game_haven_bag_proto_init() }
func file_proto_game_haven_bag_proto_init() {
	if File_proto_game_haven_bag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_haven_bag_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagEnterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagChangeRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagExitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagEditCancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagThemeChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagFurnitureOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagFurnitureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagFurnitureCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagKickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagPermissionsUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagInvitationAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagInvitationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagRoomUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagPackListEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagEditStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagEditFinishedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagDailyLotteryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagFurnitureEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagPermissionsUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagInvitationClosedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagInvitationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagInvitationOfferedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_haven_bag_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*HavenBagRoomUpdateEvent_HavenBagRoomPreview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_game_haven_bag_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_haven_bag_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_haven_bag_proto_goTypes,
		DependencyIndexes: file_proto_game_haven_bag_proto_depIdxs,
		EnumInfos:         file_proto_game_haven_bag_proto_enumTypes,
		MessageInfos:      file_proto_game_haven_bag_proto_msgTypes,
	}.Build()
	File_proto_game_haven_bag_proto = out.File
	file_proto_game_haven_bag_proto_rawDesc = nil
	file_proto_game_haven_bag_proto_goTypes = nil
	file_proto_game_haven_bag_proto_depIdxs = nil
}
