// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/game/account.proto

package account

import (
	common "go-xp-dofus-unity-proto-builder/src/protocol/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuestLimitationEvent_GuestLimitation int32

const (
	GuestLimitationEvent_LIMITED_TO_REGISTERED GuestLimitationEvent_GuestLimitation = 0
	GuestLimitationEvent_LIMIT_ON_JOB_XP       GuestLimitationEvent_GuestLimitation = 1
	GuestLimitationEvent_LIMIT_ON_JOB_USE      GuestLimitationEvent_GuestLimitation = 2
	GuestLimitationEvent_LIMIT_ON_MAP          GuestLimitationEvent_GuestLimitation = 3
	GuestLimitationEvent_LIMIT_ON_ITEM         GuestLimitationEvent_GuestLimitation = 4
	GuestLimitationEvent_LIMIT_ON_CHAT         GuestLimitationEvent_GuestLimitation = 5
	GuestLimitationEvent_LIMIT_ON_GUILD        GuestLimitationEvent_GuestLimitation = 6
)

// Enum value maps for GuestLimitationEvent_GuestLimitation.
var (
	GuestLimitationEvent_GuestLimitation_name = map[int32]string{
		0: "LIMITED_TO_REGISTERED",
		1: "LIMIT_ON_JOB_XP",
		2: "LIMIT_ON_JOB_USE",
		3: "LIMIT_ON_MAP",
		4: "LIMIT_ON_ITEM",
		5: "LIMIT_ON_CHAT",
		6: "LIMIT_ON_GUILD",
	}
	GuestLimitationEvent_GuestLimitation_value = map[string]int32{
		"LIMITED_TO_REGISTERED": 0,
		"LIMIT_ON_JOB_XP":       1,
		"LIMIT_ON_JOB_USE":      2,
		"LIMIT_ON_MAP":          3,
		"LIMIT_ON_ITEM":         4,
		"LIMIT_ON_CHAT":         5,
		"LIMIT_ON_GUILD":        6,
	}
)

func (x GuestLimitationEvent_GuestLimitation) Enum() *GuestLimitationEvent_GuestLimitation {
	p := new(GuestLimitationEvent_GuestLimitation)
	*p = x
	return p
}

func (x GuestLimitationEvent_GuestLimitation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuestLimitationEvent_GuestLimitation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_account_proto_enumTypes[0].Descriptor()
}

func (GuestLimitationEvent_GuestLimitation) Type() protoreflect.EnumType {
	return &file_proto_game_account_proto_enumTypes[0]
}

func (x GuestLimitationEvent_GuestLimitation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuestLimitationEvent_GuestLimitation.Descriptor instead.
func (GuestLimitationEvent_GuestLimitation) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{3, 0}
}

type SubscriptionLimitationEvent_SubscriptionRequired int32

const (
	SubscriptionLimitationEvent_LIMITED_TO_SUBSCRIBER SubscriptionLimitationEvent_SubscriptionRequired = 0
	SubscriptionLimitationEvent_LIMIT_ON_JOB_XP       SubscriptionLimitationEvent_SubscriptionRequired = 1
	SubscriptionLimitationEvent_LIMIT_ON_JOB_USE      SubscriptionLimitationEvent_SubscriptionRequired = 2
	SubscriptionLimitationEvent_LIMIT_ON_MAP          SubscriptionLimitationEvent_SubscriptionRequired = 3
	SubscriptionLimitationEvent_LIMIT_ON_ITEM         SubscriptionLimitationEvent_SubscriptionRequired = 4
	SubscriptionLimitationEvent_LIMIT_ON_HAVEN_BAG    SubscriptionLimitationEvent_SubscriptionRequired = 5
)

// Enum value maps for SubscriptionLimitationEvent_SubscriptionRequired.
var (
	SubscriptionLimitationEvent_SubscriptionRequired_name = map[int32]string{
		0: "LIMITED_TO_SUBSCRIBER",
		1: "LIMIT_ON_JOB_XP",
		2: "LIMIT_ON_JOB_USE",
		3: "LIMIT_ON_MAP",
		4: "LIMIT_ON_ITEM",
		5: "LIMIT_ON_HAVEN_BAG",
	}
	SubscriptionLimitationEvent_SubscriptionRequired_value = map[string]int32{
		"LIMITED_TO_SUBSCRIBER": 0,
		"LIMIT_ON_JOB_XP":       1,
		"LIMIT_ON_JOB_USE":      2,
		"LIMIT_ON_MAP":          3,
		"LIMIT_ON_ITEM":         4,
		"LIMIT_ON_HAVEN_BAG":    5,
	}
)

func (x SubscriptionLimitationEvent_SubscriptionRequired) Enum() *SubscriptionLimitationEvent_SubscriptionRequired {
	p := new(SubscriptionLimitationEvent_SubscriptionRequired)
	*p = x
	return p
}

func (x SubscriptionLimitationEvent_SubscriptionRequired) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionLimitationEvent_SubscriptionRequired) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_account_proto_enumTypes[1].Descriptor()
}

func (SubscriptionLimitationEvent_SubscriptionRequired) Type() protoreflect.EnumType {
	return &file_proto_game_account_proto_enumTypes[1]
}

func (x SubscriptionLimitationEvent_SubscriptionRequired) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionLimitationEvent_SubscriptionRequired.Descriptor instead.
func (SubscriptionLimitationEvent_SubscriptionRequired) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{5, 0}
}

type AccountInformationUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionEndDate int64 `protobuf:"varint,1,opt,name=subscription_end_date,json=subscriptionEndDate,proto3" json:"subscription_end_date,omitempty"`
}

func (x *AccountInformationUpdateEvent) Reset() {
	*x = AccountInformationUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInformationUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInformationUpdateEvent) ProtoMessage() {}

func (x *AccountInformationUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInformationUpdateEvent.ProtoReflect.Descriptor instead.
func (*AccountInformationUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInformationUpdateEvent) GetSubscriptionEndDate() int64 {
	if x != nil {
		return x.SubscriptionEndDate
	}
	return 0
}

type AccountSubscriptionElapsedDurationUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionElapsedDuration int64 `protobuf:"varint,1,opt,name=subscription_elapsed_duration,json=subscriptionElapsedDuration,proto3" json:"subscription_elapsed_duration,omitempty"`
}

func (x *AccountSubscriptionElapsedDurationUpdateEvent) Reset() {
	*x = AccountSubscriptionElapsedDurationUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountSubscriptionElapsedDurationUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSubscriptionElapsedDurationUpdateEvent) ProtoMessage() {}

func (x *AccountSubscriptionElapsedDurationUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSubscriptionElapsedDurationUpdateEvent.ProtoReflect.Descriptor instead.
func (*AccountSubscriptionElapsedDurationUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountSubscriptionElapsedDurationUpdateEvent) GetSubscriptionElapsedDuration() int64 {
	if x != nil {
		return x.SubscriptionElapsedDuration
	}
	return 0
}

type AccountCapabilitiesEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId             int64            `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TutorialAvailable     bool             `protobuf:"varint,2,opt,name=tutorial_available,json=tutorialAvailable,proto3" json:"tutorial_available,omitempty"`
	Status                common.Hierarchy `protobuf:"varint,3,opt,name=status,proto3,enum=com.ankama.dofus.server.game.protocol.common.Hierarchy" json:"status,omitempty"`
	CanCreateNewCharacter bool             `protobuf:"varint,4,opt,name=can_create_new_character,json=canCreateNewCharacter,proto3" json:"can_create_new_character,omitempty"`
}

func (x *AccountCapabilitiesEvent) Reset() {
	*x = AccountCapabilitiesEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCapabilitiesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCapabilitiesEvent) ProtoMessage() {}

func (x *AccountCapabilitiesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCapabilitiesEvent.ProtoReflect.Descriptor instead.
func (*AccountCapabilitiesEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountCapabilitiesEvent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountCapabilitiesEvent) GetTutorialAvailable() bool {
	if x != nil {
		return x.TutorialAvailable
	}
	return false
}

func (x *AccountCapabilitiesEvent) GetStatus() common.Hierarchy {
	if x != nil {
		return x.Status
	}
	return common.Hierarchy(0)
}

func (x *AccountCapabilitiesEvent) GetCanCreateNewCharacter() bool {
	if x != nil {
		return x.CanCreateNewCharacter
	}
	return false
}

type GuestLimitationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason GuestLimitationEvent_GuestLimitation `protobuf:"varint,1,opt,name=reason,proto3,enum=com.ankama.dofus.server.game.protocol.account.GuestLimitationEvent_GuestLimitation" json:"reason,omitempty"`
}

func (x *GuestLimitationEvent) Reset() {
	*x = GuestLimitationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestLimitationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestLimitationEvent) ProtoMessage() {}

func (x *GuestLimitationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestLimitationEvent.ProtoReflect.Descriptor instead.
func (*GuestLimitationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{3}
}

func (x *GuestLimitationEvent) GetReason() GuestLimitationEvent_GuestLimitation {
	if x != nil {
		return x.Reason
	}
	return GuestLimitationEvent_LIMITED_TO_REGISTERED
}

type GuestModeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Effective bool `protobuf:"varint,1,opt,name=effective,proto3" json:"effective,omitempty"`
}

func (x *GuestModeEvent) Reset() {
	*x = GuestModeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestModeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestModeEvent) ProtoMessage() {}

func (x *GuestModeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestModeEvent.ProtoReflect.Descriptor instead.
func (*GuestModeEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{4}
}

func (x *GuestModeEvent) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

type SubscriptionLimitationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason SubscriptionLimitationEvent_SubscriptionRequired `protobuf:"varint,1,opt,name=reason,proto3,enum=com.ankama.dofus.server.game.protocol.account.SubscriptionLimitationEvent_SubscriptionRequired" json:"reason,omitempty"`
}

func (x *SubscriptionLimitationEvent) Reset() {
	*x = SubscriptionLimitationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionLimitationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionLimitationEvent) ProtoMessage() {}

func (x *SubscriptionLimitationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionLimitationEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionLimitationEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionLimitationEvent) GetReason() SubscriptionLimitationEvent_SubscriptionRequired {
	if x != nil {
		return x.Reason
	}
	return SubscriptionLimitationEvent_LIMITED_TO_SUBSCRIBER
}

type SubscriptionZoneEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Effective bool `protobuf:"varint,1,opt,name=effective,proto3" json:"effective,omitempty"`
}

func (x *SubscriptionZoneEvent) Reset() {
	*x = SubscriptionZoneEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionZoneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionZoneEvent) ProtoMessage() {}

func (x *SubscriptionZoneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionZoneEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionZoneEvent) Descriptor() ([]byte, []int) {
	return file_proto_game_account_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionZoneEvent) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

var File_proto_game_account_proto protoreflect.FileDescriptor

var file_proto_game_account_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x1d, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x73, 0x0a, 0x2d,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a,
	0x1d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6c,
	0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x1b, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xf2, 0x01, 0x0a, 0x18, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a,
	0x12, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x74, 0x75, 0x74, 0x6f, 0x72,
	0x69, 0x61, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x4f, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x65, 0x72,
	0x61, 0x72, 0x63, 0x68, 0x79, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a,
	0x18, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x65, 0x77, 0x5f,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x15, 0x63, 0x61, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0xa9, 0x02, 0x0a, 0x14, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x6b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x53, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x64, 0x6f, 0x66,
	0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x47, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xa3, 0x01, 0x0a,
	0x0f, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x0a, 0x15, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c,
	0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x4a, 0x4f, 0x42, 0x5f, 0x58, 0x50, 0x10, 0x01,
	0x12, 0x14, 0x0a, 0x10, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x4a, 0x4f, 0x42,
	0x5f, 0x55, 0x53, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f,
	0x4f, 0x4e, 0x5f, 0x4d, 0x41, 0x50, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x49, 0x4d, 0x49,
	0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4c,
	0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x05, 0x12, 0x12,
	0x0a, 0x0e, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x47, 0x55, 0x49, 0x4c, 0x44,
	0x10, 0x06, 0x22, 0x2e, 0x0a, 0x0e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x22, 0xb2, 0x02, 0x0a, 0x1b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x77, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x5f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x64, 0x6f, 0x66, 0x75, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x14,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x45, 0x44, 0x5f,
	0x54, 0x4f, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x52, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x4a, 0x4f, 0x42, 0x5f,
	0x58, 0x50, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e,
	0x5f, 0x4a, 0x4f, 0x42, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x49,
	0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x4d, 0x41, 0x50, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d,
	0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x04, 0x12,
	0x16, 0x0a, 0x12, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x48, 0x41, 0x56, 0x45,
	0x4e, 0x5f, 0x42, 0x41, 0x47, 0x10, 0x05, 0x22, 0x35, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x6f, 0x2d, 0x78, 0x70, 0x2d, 0x64, 0x6f, 0x66, 0x75, 0x73, 0x2d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65,
	0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_game_account_proto_rawDescOnce sync.Once
	file_proto_game_account_proto_rawDescData = file_proto_game_account_proto_rawDesc
)

func file_proto_game_account_proto_rawDescGZIP() []byte {
	file_proto_game_account_proto_rawDescOnce.Do(func() {
		file_proto_game_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_account_proto_rawDescData)
	})
	return file_proto_game_account_proto_rawDescData
}

var file_proto_game_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_game_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_game_account_proto_goTypes = []any{
	(GuestLimitationEvent_GuestLimitation)(0),             // 0: com.ankama.dofus.server.game.protocol.account.GuestLimitationEvent.GuestLimitation
	(SubscriptionLimitationEvent_SubscriptionRequired)(0), // 1: com.ankama.dofus.server.game.protocol.account.SubscriptionLimitationEvent.SubscriptionRequired
	(*AccountInformationUpdateEvent)(nil),                 // 2: com.ankama.dofus.server.game.protocol.account.AccountInformationUpdateEvent
	(*AccountSubscriptionElapsedDurationUpdateEvent)(nil), // 3: com.ankama.dofus.server.game.protocol.account.AccountSubscriptionElapsedDurationUpdateEvent
	(*AccountCapabilitiesEvent)(nil),                      // 4: com.ankama.dofus.server.game.protocol.account.AccountCapabilitiesEvent
	(*GuestLimitationEvent)(nil),                          // 5: com.ankama.dofus.server.game.protocol.account.GuestLimitationEvent
	(*GuestModeEvent)(nil),                                // 6: com.ankama.dofus.server.game.protocol.account.GuestModeEvent
	(*SubscriptionLimitationEvent)(nil),                   // 7: com.ankama.dofus.server.game.protocol.account.SubscriptionLimitationEvent
	(*SubscriptionZoneEvent)(nil),                         // 8: com.ankama.dofus.server.game.protocol.account.SubscriptionZoneEvent
	(common.Hierarchy)(0),                                 // 9: com.ankama.dofus.server.game.protocol.common.Hierarchy
}
var file_proto_game_account_proto_depIdxs = []int32{
	9, // 0: com.ankama.dofus.server.game.protocol.account.AccountCapabilitiesEvent.status:type_name -> com.ankama.dofus.server.game.protocol.common.Hierarchy
	0, // 1: com.ankama.dofus.server.game.protocol.account.GuestLimitationEvent.reason:type_name -> com.ankama.dofus.server.game.protocol.account.GuestLimitationEvent.GuestLimitation
	1, // 2: com.ankama.dofus.server.game.protocol.account.SubscriptionLimitationEvent.reason:type_name -> com.ankama.dofus.server.game.protocol.account.SubscriptionLimitationEvent.SubscriptionRequired
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_game_account_proto_init() }
func file_proto_game_account_proto_init() {
	if File_proto_game_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccountInformationUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccountSubscriptionElapsedDurationUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AccountCapabilitiesEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GuestLimitationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GuestModeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SubscriptionLimitationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_account_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SubscriptionZoneEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_account_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_account_proto_goTypes,
		DependencyIndexes: file_proto_game_account_proto_depIdxs,
		EnumInfos:         file_proto_game_account_proto_enumTypes,
		MessageInfos:      file_proto_game_account_proto_msgTypes,
	}.Build()
	File_proto_game_account_proto = out.File
	file_proto_game_account_proto_rawDesc = nil
	file_proto_game_account_proto_goTypes = nil
	file_proto_game_account_proto_depIdxs = nil
}
